package com.geoland.kfis.model.view;

// Generated Oct 13, 2015 11:18:25 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * ShapeFieldsControlView generated by hbm2java.
 */
@Entity
@Table(name = "shape_fields_control", schema = "public")
public class ShapeFieldsControlView implements java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private ShapeFieldsControlViewId id;

	/**
	 * Instantiates a new shape fields control view.
	 */
	public ShapeFieldsControlView() {
	}

	/**
	 * Instantiates a new shape fields control view.
	 *
	 * @param id the id
	 */
	public ShapeFieldsControlView(ShapeFieldsControlViewId id) {
		this.id = id;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "standId", column = @Column(name = "stand_id", length = 254)),
			@AttributeOverride(name = "field", column = @Column(name = "field")),
			@AttributeOverride(name = "value", column = @Column(name = "value", precision = 131089, scale = 0)) })
	public ShapeFieldsControlViewId getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(ShapeFieldsControlViewId id) {
		this.id = id;
	}

}
