package com.geoland.kfis.model;

// Generated Mar 3, 2016 4:36:32 PM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * ActivityDomain generated by hbm2java.
 */
@Entity
@Table(name = "tfrm_activity_domain", schema = "public")
public class ActivityDomain extends AbstractPersistentObject implements
		java.io.Serializable {

	/** The id. */
	private Long id;
	
	/** The activity domain. */
	private ActivityDomain activityDomain;
	
	/** The code. */
	private String code;
	
	/** The name al. */
	private String nameAl;
	
	/** The name en. */
	private String nameEn;
	
	/** The name sr. */
	private String nameSr;
	
	/** The type. */
	private String type;
	
	/** The sort. */
	private Short sort;
	
	/** The activity domains. */
	private Set<ActivityDomain> activityDomains = new HashSet<ActivityDomain>(0);
	
	/** The activities. */
	private Set<Activity> activities = new HashSet<Activity>(0);

	/**
	 * Instantiates a new activity domain.
	 */
	public ActivityDomain() {
	}

	/**
	 * Instantiates a new activity domain.
	 *
	 * @param nameAl the name al
	 * @param nameEn the name en
	 * @param nameSr the name sr
	 * @param type the type
	 * @param sort the sort
	 */
	public ActivityDomain(String nameAl, String nameEn, String nameSr,
			String type, Short sort) {
		this.nameAl = nameAl;
		this.nameEn = nameEn;
		this.nameSr = nameSr;
		this.type = type;
		this.sort = sort;
	}

	/**
	 * Instantiates a new activity domain.
	 *
	 * @param activityDomain the activity domain
	 * @param code the code
	 * @param nameAl the name al
	 * @param nameEn the name en
	 * @param nameSr the name sr
	 * @param type the type
	 * @param sort the sort
	 * @param activityDomains the activity domains
	 * @param activities the activities
	 */
	public ActivityDomain(ActivityDomain activityDomain, String code,
			String nameAl, String nameEn, String nameSr, String type,
			Short sort, Set<ActivityDomain> activityDomains,
			Set<Activity> activities) {
		this.activityDomain = activityDomain;
		this.code = code;
		this.nameAl = nameAl;
		this.nameEn = nameEn;
		this.nameSr = nameSr;
		this.type = type;
		this.sort = sort;
		this.activityDomains = activityDomains;
		this.activities = activities;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the activity domain.
	 *
	 * @return the activity domain
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public ActivityDomain getActivityDomain() {
		return this.activityDomain;
	}

	/**
	 * Sets the activity domain.
	 *
	 * @param activityDomain the new activity domain
	 */
	public void setActivityDomain(ActivityDomain activityDomain) {
		this.activityDomain = activityDomain;
	}

	/**
	 * Gets the code.
	 *
	 * @return the code
	 */
	@Column(name = "code", length = 5)
	public String getCode() {
		return this.code;
	}

	/**
	 * Sets the code.
	 *
	 * @param code the new code
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * Gets the name al.
	 *
	 * @return the name al
	 */
	@Column(name = "name_al", nullable = false, length = 50)
	public String getNameAl() {
		return this.nameAl;
	}

	/**
	 * Sets the name al.
	 *
	 * @param nameAl the new name al
	 */
	public void setNameAl(String nameAl) {
		this.nameAl = nameAl;
	}

	/**
	 * Gets the name en.
	 *
	 * @return the name en
	 */
	@Column(name = "name_en", nullable = false, length = 50)
	public String getNameEn() {
		return this.nameEn;
	}

	/**
	 * Sets the name en.
	 *
	 * @param nameEn the new name en
	 */
	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	/**
	 * Gets the name sr.
	 *
	 * @return the name sr
	 */
	@Column(name = "name_sr", nullable = false, length = 50)
	public String getNameSr() {
		return this.nameSr;
	}

	/**
	 * Sets the name sr.
	 *
	 * @param nameSr the new name sr
	 */
	public void setNameSr(String nameSr) {
		this.nameSr = nameSr;
	}

	/**
	 * Gets the type.
	 *
	 * @return the type
	 */
	@Column(name = "type", nullable = false, length = 1)
	public String getType() {
		return this.type;
	}

	/**
	 * Sets the type.
	 *
	 * @param type the new type
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Gets the sort.
	 *
	 * @return the sort
	 */
	@Column(name = "sort", nullable = false)
	public Short getSort() {
		return this.sort;
	}

	/**
	 * Sets the sort.
	 *
	 * @param sort the new sort
	 */
	public void setSort(Short sort) {
		this.sort = sort;
	}

	/**
	 * Gets the activity domains.
	 *
	 * @return the activity domains
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activityDomain")
	public Set<ActivityDomain> getActivityDomains() {
		return this.activityDomains;
	}

	/**
	 * Sets the activity domains.
	 *
	 * @param activityDomains the new activity domains
	 */
	public void setActivityDomains(Set<ActivityDomain> activityDomains) {
		this.activityDomains = activityDomains;
	}

	/**
	 * Gets the activities.
	 *
	 * @return the activities
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activityDomain")
	public Set<Activity> getActivities() {
		return this.activities;
	}

	/**
	 * Sets the activities.
	 *
	 * @param activities the new activities
	 */
	public void setActivities(Set<Activity> activities) {
		this.activities = activities;
	}

}
