package com.geoland.kfis.model;

// Generated Feb 11, 2015 2:26:59 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import com.geoland.framework.persistence.base.AbstractPersistentObject;

// TODO: Auto-generated Javadoc
/**
 * AlertRule generated by hbm2java.
 */
@Entity
@Table(name = "talertrule", schema = "public")
public class AlertRule extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The person by updatedby. */
	private Person personByUpdatedby;
	
	/** The person by createdby. */
	private Person personByCreatedby;
	
	/** The organisation. */
	private Organisation organisation;
	
	/** The isactive. */
	private String isactive;
	
	/** The created. */
	private Date created;
	
	/** The updated. */
	private Date updated;
	
	/** The name. */
	private String name;
	
	/** The action. */
	private String action;
	
	/** The filterclause. */
	private String filterclause;
	
	/** The sql str. */
	private String sqlStr;
	
	/** The type str. */
	private String typeStr;
	
	/** The alert rule trls. */
	private Set<AlertRuleTrl> alertRuleTrls = new HashSet<AlertRuleTrl>(0);
	
	/** The alert recipients. */
	private Set<AlertRecipient> alertRecipients = new HashSet<AlertRecipient>(0);
	
	/** The alerts. */
	private Set<Alert> alerts = new HashSet<Alert>(0);

	/**
	 * Instantiates a new alert rule.
	 */
	public AlertRule() {
	}

	/**
	 * Instantiates a new alert rule.
	 *
	 * @param personByUpdatedby the person by updatedby
	 * @param personByCreatedby the person by createdby
	 * @param organisation the organisation
	 * @param isactive the isactive
	 * @param created the created
	 * @param updated the updated
	 * @param name the name
	 */
	public AlertRule(Person personByUpdatedby, Person personByCreatedby,
			Organisation organisation, String isactive, Date created,
			Date updated, String name) {
		this.personByUpdatedby = personByUpdatedby;
		this.personByCreatedby = personByCreatedby;
		this.organisation = organisation;
		this.isactive = isactive;
		this.created = created;
		this.updated = updated;
		this.name = name;
	}

	/**
	 * Instantiates a new alert rule.
	 *
	 * @param personByUpdatedby the person by updatedby
	 * @param personByCreatedby the person by createdby
	 * @param organisation the organisation
	 * @param isactive the isactive
	 * @param created the created
	 * @param updated the updated
	 * @param name the name
	 * @param action the action
	 * @param filterclause the filterclause
	 * @param sqlStr the sql str
	 * @param typeStr the type str
	 * @param alertRuleTrls the alert rule trls
	 * @param alertRecipients the alert recipients
	 * @param alerts the alerts
	 */
	public AlertRule(Person personByUpdatedby, Person personByCreatedby,
			Organisation organisation, String isactive, Date created,
			Date updated, String name, String action, String filterclause,
			String sqlStr, String typeStr, Set<AlertRuleTrl> alertRuleTrls,
			Set<AlertRecipient> alertRecipients, Set<Alert> alerts) {
		this.personByUpdatedby = personByUpdatedby;
		this.personByCreatedby = personByCreatedby;
		this.organisation = organisation;
		this.isactive = isactive;
		this.created = created;
		this.updated = updated;
		this.name = name;
		this.action = action;
		this.filterclause = filterclause;
		this.sqlStr = sqlStr;
		this.typeStr = typeStr;
		this.alertRuleTrls = alertRuleTrls;
		this.alertRecipients = alertRecipients;
		this.alerts = alerts;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the person by updatedby.
	 *
	 * @return the person by updatedby
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedby", nullable = false)
	public Person getPersonByUpdatedby() {
		return this.personByUpdatedby;
	}

	/**
	 * Sets the person by updatedby.
	 *
	 * @param personByUpdatedby the new person by updatedby
	 */
	public void setPersonByUpdatedby(Person personByUpdatedby) {
		this.personByUpdatedby = personByUpdatedby;
	}

	/**
	 * Gets the person by createdby.
	 *
	 * @return the person by createdby
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "createdby", nullable = false)
	public Person getPersonByCreatedby() {
		return this.personByCreatedby;
	}

	/**
	 * Sets the person by createdby.
	 *
	 * @param personByCreatedby the new person by createdby
	 */
	public void setPersonByCreatedby(Person personByCreatedby) {
		this.personByCreatedby = personByCreatedby;
	}

	/**
	 * Gets the organisation.
	 *
	 * @return the organisation
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_id", nullable = false)
	public Organisation getOrganisation() {
		return this.organisation;
	}

	/**
	 * Sets the organisation.
	 *
	 * @param organisation the new organisation
	 */
	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	/**
	 * Gets the isactive.
	 *
	 * @return the isactive
	 */
	@Column(name = "isactive", nullable = false, length = 1)
	public String getIsactive() {
		return this.isactive;
	}

	/**
	 * Sets the isactive.
	 *
	 * @param isactive the new isactive
	 */
	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

	/**
	 * Gets the created.
	 *
	 * @return the created
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	/**
	 * Sets the created.
	 *
	 * @param created the new created
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * Gets the updated.
	 *
	 * @return the updated
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	/**
	 * Sets the updated.
	 *
	 * @param updated the new updated
	 */
	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the action.
	 *
	 * @return the action
	 */
	@Column(name = "action", length = 60)
	public String getAction() {
		return this.action;
	}

	/**
	 * Sets the action.
	 *
	 * @param action the new action
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * Gets the filterclause.
	 *
	 * @return the filterclause
	 */
	@Column(name = "filterclause", length = 2000)
	public String getFilterclause() {
		return this.filterclause;
	}

	/**
	 * Sets the filterclause.
	 *
	 * @param filterclause the new filterclause
	 */
	public void setFilterclause(String filterclause) {
		this.filterclause = filterclause;
	}

	/**
	 * Gets the sql str.
	 *
	 * @return the sql str
	 */
	@Column(name = "sql_str", length = 2000)
	public String getSqlStr() {
		return this.sqlStr;
	}

	/**
	 * Sets the sql str.
	 *
	 * @param sqlStr the new sql str
	 */
	public void setSqlStr(String sqlStr) {
		this.sqlStr = sqlStr;
	}

	/**
	 * Gets the type str.
	 *
	 * @return the type str
	 */
	@Column(name = "type_str", length = 60)
	public String getTypeStr() {
		return this.typeStr;
	}

	/**
	 * Sets the type str.
	 *
	 * @param typeStr the new type str
	 */
	public void setTypeStr(String typeStr) {
		this.typeStr = typeStr;
	}

	/**
	 * Gets the alert rule trls.
	 *
	 * @return the alert rule trls
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alertRule")
	public Set<AlertRuleTrl> getAlertRuleTrls() {
		return this.alertRuleTrls;
	}

	/**
	 * Sets the alert rule trls.
	 *
	 * @param alertRuleTrls the new alert rule trls
	 */
	public void setAlertRuleTrls(Set<AlertRuleTrl> alertRuleTrls) {
		this.alertRuleTrls = alertRuleTrls;
	}

	/**
	 * Gets the alert recipients.
	 *
	 * @return the alert recipients
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alertRule")
	public Set<AlertRecipient> getAlertRecipients() {
		return this.alertRecipients;
	}

	/**
	 * Sets the alert recipients.
	 *
	 * @param alertRecipients the new alert recipients
	 */
	public void setAlertRecipients(Set<AlertRecipient> alertRecipients) {
		this.alertRecipients = alertRecipients;
	}

	/**
	 * Gets the alerts.
	 *
	 * @return the alerts
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "alertRule")
	public Set<Alert> getAlerts() {
		return this.alerts;
	}

	/**
	 * Sets the alerts.
	 *
	 * @param alerts the new alerts
	 */
	public void setAlerts(Set<Alert> alerts) {
		this.alerts = alerts;
	}

}
