package com.geoland.kfis.model;

// Generated Dec 23, 2014 10:34:48 AM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * AnnualPlanningActivity generated by hbm2java.
 */
@Entity
@Table(name = "tfrm_annual_planning_activity", schema = "public")
public class AnnualPlanningActivity extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The annual plan id. */
	private Long annualPlanId;
	
	/** The activity id. */
	private Long activityId;

	/**
	 * Instantiates a new annual planning activity.
	 */
	public AnnualPlanningActivity() {
	}

	/**
	 * Instantiates a new annual planning activity.
	 *
	 * @param annualPlanId the annual plan id
	 * @param activityId the activity id
	 */
	public AnnualPlanningActivity(Long annualPlanId, Long activityId) {
		this.annualPlanId = annualPlanId;
		this.activityId = activityId;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the annual plan id.
	 *
	 * @return the annual plan id
	 */
	@Column(name = "annual_plan_id", nullable = false)
	public Long getAnnualPlanId() {
		return this.annualPlanId;
	}

	/**
	 * Sets the annual plan id.
	 *
	 * @param annualPlanId the new annual plan id
	 */
	public void setAnnualPlanId(Long annualPlanId) {
		this.annualPlanId = annualPlanId;
	}

	/**
	 * Gets the activity id.
	 *
	 * @return the activity id
	 */
	@Column(name = "activity_id", nullable = false)
	public Long getActivityId() {
		return this.activityId;
	}

	/**
	 * Sets the activity id.
	 *
	 * @param activityId the new activity id
	 */
	public void setActivityId(Long activityId) {
		this.activityId = activityId;
	}

}
