package com.geoland.kfis.model;

// Generated Feb 11, 2015 2:26:59 AM by Hibernate Tools 3.4.0.CR1

import com.geoland.framework.persistence.base.*;
import org.hibernate.annotations.Type;
import com.geoland.kfis.persistence.hibernate.usertypes.Activitystatus;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * AnnualPlanningStatus generated by hbm2java.
 */
@Entity
@Table(name = "tfrm_annual_planning_status", schema = "public")
public class AnnualPlanningStatus extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The person. */
	private Person person;
	
	/** The annual planning. */
	private AnnualPlanning annualPlanning;
	
	/** The status. */
	private Activitystatus status;
	
	/** The created date. */
	private Date createdDate;
	
	/** The remarks. */
	private String remarks;
	
	/** The annual plannings. */
	private Set<AnnualPlanning> annualPlannings = new HashSet<AnnualPlanning>(0);

	/**
	 * Instantiates a new annual planning status.
	 */
	public AnnualPlanningStatus() {
	}

	/**
	 * Instantiates a new annual planning status.
	 *
	 * @param person the person
	 * @param annualPlanning the annual planning
	 * @param status the status
	 * @param createdDate the created date
	 */
	public AnnualPlanningStatus(Person person, AnnualPlanning annualPlanning,
			Activitystatus status, Date createdDate) {
		this.person = person;
		this.annualPlanning = annualPlanning;
		this.status = status;
		this.createdDate = createdDate;
	}

	/**
	 * Instantiates a new annual planning status.
	 *
	 * @param person the person
	 * @param annualPlanning the annual planning
	 * @param status the status
	 * @param createdDate the created date
	 * @param remarks the remarks
	 * @param annualPlannings the annual plannings
	 */
	public AnnualPlanningStatus(Person person, AnnualPlanning annualPlanning,
			Activitystatus status, Date createdDate, String remarks,
			Set<AnnualPlanning> annualPlannings) {
		this.person = person;
		this.annualPlanning = annualPlanning;
		this.status = status;
		this.createdDate = createdDate;
		this.remarks = remarks;
		this.annualPlannings = annualPlannings;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the person.
	 *
	 * @return the person
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	/**
	 * Sets the person.
	 *
	 * @param person the new person
	 */
	public void setPerson(Person person) {
		this.person = person;
	}

	/**
	 * Gets the annual planning.
	 *
	 * @return the annual planning
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "annual_planning_id", nullable = false)
	public AnnualPlanning getAnnualPlanning() {
		return this.annualPlanning;
	}

	/**
	 * Sets the annual planning.
	 *
	 * @param annualPlanning the new annual planning
	 */
	public void setAnnualPlanning(AnnualPlanning annualPlanning) {
		this.annualPlanning = annualPlanning;
	}

	/**
	 * Gets the status.
	 *
	 * @return the status
	 */
	@Column(name = "status", nullable = false, length = 6)
	@Type(type = "com.geoland.kfis.persistence.hibernate.usertypes.ActivitystatusUserType")
	public Activitystatus getStatus() {
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(Activitystatus status) {
		this.status = status;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * Gets the remarks.
	 *
	 * @return the remarks
	 */
	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Sets the remarks.
	 *
	 * @param remarks the new remarks
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Gets the annual plannings.
	 *
	 * @return the annual plannings
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "annualPlanningStatus")
	public Set<AnnualPlanning> getAnnualPlannings() {
		return this.annualPlannings;
	}

	/**
	 * Sets the annual plannings.
	 *
	 * @param annualPlannings the new annual plannings
	 */
	public void setAnnualPlannings(Set<AnnualPlanning> annualPlannings) {
		this.annualPlannings = annualPlannings;
	}

}
