package com.geoland.kfis.model;

// Generated Oct 16, 2015 2:27:02 PM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.spatial.GeometryType;
import com.vividsolutions.jts.geom.Geometry;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * Biodiversity generated by hbm2java.
 */
@Entity
@Table(name = "tgis_biodiv", schema = "public")
@TypeDef(name = "geometry", typeClass = GeometryType.class)
public class Biodiversity extends AbstractPersistentObject implements
		java.io.Serializable {

	/** The id. */
	private Long id;
	
	/** The stand. */
	private Stand stand;
	
	/** The biodiversity name. */
	private BiodiversityName biodiversityName;
	
	/** The remarks. */
	private String remarks;
	
	/** The comp nr. */
	private String compNr;
	
	/** The stand nr. */
	private String standNr;
	
	/** The timeform. */
	private String timeform;
	
	/** The taksator. */
	private String taksator;
	
	/** The geom. */
	private Geometry theGeom;

	/**
	 * Instantiates a new biodiversity.
	 */
	public Biodiversity() {
	}

	/**
	 * Instantiates a new biodiversity.
	 *
	 * @param stand the stand
	 * @param biodiversityName the biodiversity name
	 * @param remarks the remarks
	 * @param compNr the comp nr
	 * @param standNr the stand nr
	 * @param timeform the timeform
	 * @param taksator the taksator
	 * @param theGeom the the geom
	 */
	public Biodiversity(Stand stand, BiodiversityName biodiversityName,
			String remarks, String compNr, String standNr, String timeform,
			String taksator, Geometry theGeom) {
		this.stand = stand;
		this.biodiversityName = biodiversityName;
		this.remarks = remarks;
		this.compNr = compNr;
		this.standNr = standNr;
		this.timeform = timeform;
		this.taksator = taksator;
		this.theGeom = theGeom;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the stand.
	 *
	 * @return the stand
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stand_id")
	public Stand getStand() {
		return this.stand;
	}

	/**
	 * Sets the stand.
	 *
	 * @param stand the new stand
	 */
	public void setStand(Stand stand) {
		this.stand = stand;
	}

	/**
	 * Gets the biodiversity name.
	 *
	 * @return the biodiversity name
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "biodiv_id")
	public BiodiversityName getBiodiversityName() {
		return this.biodiversityName;
	}

	/**
	 * Sets the biodiversity name.
	 *
	 * @param biodiversityName the new biodiversity name
	 */
	public void setBiodiversityName(BiodiversityName biodiversityName) {
		this.biodiversityName = biodiversityName;
	}

	/**
	 * Gets the remarks.
	 *
	 * @return the remarks
	 */
	@Column(name = "remarks", length = 150)
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Sets the remarks.
	 *
	 * @param remarks the new remarks
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Gets the comp nr.
	 *
	 * @return the comp nr
	 */
	@Column(name = "comp_nr", length = 3)
	public String getCompNr() {
		return this.compNr;
	}

	/**
	 * Sets the comp nr.
	 *
	 * @param compNr the new comp nr
	 */
	public void setCompNr(String compNr) {
		this.compNr = compNr;
	}

	/**
	 * Gets the stand nr.
	 *
	 * @return the stand nr
	 */
	@Column(name = "stand_nr", length = 3)
	public String getStandNr() {
		return this.standNr;
	}

	/**
	 * Sets the stand nr.
	 *
	 * @param standNr the new stand nr
	 */
	public void setStandNr(String standNr) {
		this.standNr = standNr;
	}

	/**
	 * Gets the timeform.
	 *
	 * @return the timeform
	 */
	@Column(name = "timeform", length = 10)
	public String getTimeform() {
		return this.timeform;
	}

	/**
	 * Sets the timeform.
	 *
	 * @param timeform the new timeform
	 */
	public void setTimeform(String timeform) {
		this.timeform = timeform;
	}

	/**
	 * Gets the taksator.
	 *
	 * @return the taksator
	 */
	@Column(name = "taksator", length = 25)
	public String getTaksator() {
		return this.taksator;
	}

	/**
	 * Sets the taksator.
	 *
	 * @param taksator the new taksator
	 */
	public void setTaksator(String taksator) {
		this.taksator = taksator;
	}

	/**
	 * Gets the the geom.
	 *
	 * @return the the geom
	 */
	@Column(name = "the_geom")
	@Type(type = "org.hibernate.spatial.GeometryType")
	public Geometry getTheGeom() {
		return this.theGeom;
	}

	/**
	 * Sets the the geom.
	 *
	 * @param theGeom the new the geom
	 */
	public void setTheGeom(Geometry theGeom) {
		this.theGeom = theGeom;
	}

}
