package com.geoland.kfis.model;

// Generated Oct 6, 2015 3:26:51 PM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.spatial.GeometryType;
import com.vividsolutions.jts.geom.Geometry;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

// TODO: Auto-generated Javadoc
/**
 * Compartment generated by hbm2java.
 */
@Entity
@Table(name = "tgis_compartment", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = {
		"mu_id", "mup_id", "comp_nr" }))
@TypeDef(name = "geometry", typeClass = GeometryType.class)
public class Compartment extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The cadastral municipality. */
	private CadastralMunicipality cadastralMunicipality;
	
	/** The management unit. */
	private ManagementUnit managementUnit;
	
	/** The management unit period. */
	private ManagementUnitPeriod managementUnitPeriod;
	
	/** The comp nr. */
	private String compNr;
	
	/** The remarks. */
	private String remarks;
	
	/** The geom. */
	private Geometry theGeom;
	
	/** The stands. */
	private Set<Stand> stands = new HashSet<Stand>(0);
	
	/** The fire detailses. */
	private Set<FireDetails> fireDetailses = new HashSet<FireDetails>(0);

	/**
	 * Instantiates a new compartment.
	 */
	public Compartment() {
	}

	/**
	 * Instantiates a new compartment.
	 *
	 * @param cadastralMunicipality the cadastral municipality
	 * @param managementUnit the management unit
	 * @param managementUnitPeriod the management unit period
	 * @param compNr the comp nr
	 */
	public Compartment(CadastralMunicipality cadastralMunicipality,
			ManagementUnit managementUnit,
			ManagementUnitPeriod managementUnitPeriod, String compNr) {
		this.cadastralMunicipality = cadastralMunicipality;
		this.managementUnit = managementUnit;
		this.managementUnitPeriod = managementUnitPeriod;
		this.compNr = compNr;
	}

	/**
	 * Instantiates a new compartment.
	 *
	 * @param cadastralMunicipality the cadastral municipality
	 * @param managementUnit the management unit
	 * @param managementUnitPeriod the management unit period
	 * @param compNr the comp nr
	 * @param remarks the remarks
	 * @param theGeom the the geom
	 * @param stands the stands
	 * @param fireDetailses the fire detailses
	 */
	public Compartment(CadastralMunicipality cadastralMunicipality,
			ManagementUnit managementUnit,
			ManagementUnitPeriod managementUnitPeriod, String compNr,
			String remarks, Geometry theGeom, Set<Stand> stands,
			Set<FireDetails> fireDetailses) {
		this.cadastralMunicipality = cadastralMunicipality;
		this.managementUnit = managementUnit;
		this.managementUnitPeriod = managementUnitPeriod;
		this.compNr = compNr;
		this.remarks = remarks;
		this.theGeom = theGeom;
		this.stands = stands;
		this.fireDetailses = fireDetailses;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the cadastral municipality.
	 *
	 * @return the cadastral municipality
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mun_id", nullable = false)
	public CadastralMunicipality getCadastralMunicipality() {
		return this.cadastralMunicipality;
	}

	/**
	 * Sets the cadastral municipality.
	 *
	 * @param cadastralMunicipality the new cadastral municipality
	 */
	public void setCadastralMunicipality(
			CadastralMunicipality cadastralMunicipality) {
		this.cadastralMunicipality = cadastralMunicipality;
	}

	/**
	 * Gets the management unit.
	 *
	 * @return the management unit
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mu_id", nullable = false)
	public ManagementUnit getManagementUnit() {
		return this.managementUnit;
	}

	/**
	 * Sets the management unit.
	 *
	 * @param managementUnit the new management unit
	 */
	public void setManagementUnit(ManagementUnit managementUnit) {
		this.managementUnit = managementUnit;
	}

	/**
	 * Gets the management unit period.
	 *
	 * @return the management unit period
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mup_id", nullable = false)
	public ManagementUnitPeriod getManagementUnitPeriod() {
		return this.managementUnitPeriod;
	}

	/**
	 * Sets the management unit period.
	 *
	 * @param managementUnitPeriod the new management unit period
	 */
	public void setManagementUnitPeriod(
			ManagementUnitPeriod managementUnitPeriod) {
		this.managementUnitPeriod = managementUnitPeriod;
	}

	/**
	 * Gets the comp nr.
	 *
	 * @return the comp nr
	 */
	@Column(name = "comp_nr", nullable = false, length = 3)
	public String getCompNr() {
		return this.compNr;
	}

	/**
	 * Sets the comp nr.
	 *
	 * @param compNr the new comp nr
	 */
	public void setCompNr(String compNr) {
		this.compNr = compNr;
	}

	/**
	 * Gets the remarks.
	 *
	 * @return the remarks
	 */
	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	/**
	 * Sets the remarks.
	 *
	 * @param remarks the new remarks
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * Gets the the geom.
	 *
	 * @return the the geom
	 */
	@Column(name = "the_geom")
	@Type(type = "org.hibernate.spatial.GeometryType")
	public Geometry getTheGeom() {
		return this.theGeom;
	}

	/**
	 * Sets the the geom.
	 *
	 * @param theGeom the new the geom
	 */
	public void setTheGeom(Geometry theGeom) {
		this.theGeom = theGeom;
	}

	/**
	 * Gets the stands.
	 *
	 * @return the stands
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compartment")
	public Set<Stand> getStands() {
		return this.stands;
	}

	/**
	 * Sets the stands.
	 *
	 * @param stands the new stands
	 */
	public void setStands(Set<Stand> stands) {
		this.stands = stands;
	}

	/**
	 * Gets the fire detailses.
	 *
	 * @return the fire detailses
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compartment")
	public Set<FireDetails> getFireDetailses() {
		return this.fireDetailses;
	}

	/**
	 * Sets the fire detailses.
	 *
	 * @param fireDetailses the new fire detailses
	 */
	public void setFireDetailses(Set<FireDetails> fireDetailses) {
		this.fireDetailses = fireDetailses;
	}

}
