package com.geoland.kfis.model;

// Generated Dec 15, 2015 8:50:06 AM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import org.hibernate.annotations.Type;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * DhpetHuntedAnimals generated by hbm2java.
 */
@Entity
@Table(name = "tdhpet_hunted_animals", schema = "public")
public class DhpetHuntedAnimals extends AbstractPersistentObject implements
		java.io.Serializable {

	/** The id. */
	private Long id;
	
	/** The dhpet wild animals. */
	private DhpetWildAnimals dhpetWildAnimals;
	
	/** The employee. */
	private Employee employee;
	
	/** The dhpet annual plan. */
	private DhpetAnnualPlan dhpetAnnualPlan;
	
	/** The date. */
	private Date date;
	
	/** The animals number. */
	private Long animalsNumber;
	
	/** The created date. */
	private Date createdDate;
	
	/** The dhpet hunted animal details. */
	private Set<DhpetHuntedAnimalDetail> dhpetHuntedAnimalDetails = new HashSet<DhpetHuntedAnimalDetail>(
			0);

	/**
	 * Instantiates a new dhpet hunted animals.
	 */
	public DhpetHuntedAnimals() {
	}

	/**
	 * Instantiates a new dhpet hunted animals.
	 *
	 * @param dhpetWildAnimals the dhpet wild animals
	 * @param employee the employee
	 * @param dhpetAnnualPlan the dhpet annual plan
	 * @param date the date
	 * @param animalsNumber the animals number
	 * @param createdDate the created date
	 */
	public DhpetHuntedAnimals(DhpetWildAnimals dhpetWildAnimals,
			Employee employee, DhpetAnnualPlan dhpetAnnualPlan, Date date,
			Long animalsNumber, Date createdDate) {
		this.dhpetWildAnimals = dhpetWildAnimals;
		this.employee = employee;
		this.dhpetAnnualPlan = dhpetAnnualPlan;
		this.date = date;
		this.animalsNumber = animalsNumber;
		this.createdDate = createdDate;
	}

	/**
	 * Instantiates a new dhpet hunted animals.
	 *
	 * @param dhpetWildAnimals the dhpet wild animals
	 * @param employee the employee
	 * @param dhpetAnnualPlan the dhpet annual plan
	 * @param date the date
	 * @param animalsNumber the animals number
	 * @param createdDate the created date
	 * @param dhpetHuntedAnimalDetails the dhpet hunted animal details
	 */
	public DhpetHuntedAnimals(DhpetWildAnimals dhpetWildAnimals,
			Employee employee, DhpetAnnualPlan dhpetAnnualPlan, Date date,
			Long animalsNumber, Date createdDate,
			Set<DhpetHuntedAnimalDetail> dhpetHuntedAnimalDetails) {
		this.dhpetWildAnimals = dhpetWildAnimals;
		this.employee = employee;
		this.dhpetAnnualPlan = dhpetAnnualPlan;
		this.date = date;
		this.animalsNumber = animalsNumber;
		this.createdDate = createdDate;
		this.dhpetHuntedAnimalDetails = dhpetHuntedAnimalDetails;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the dhpet wild animals.
	 *
	 * @return the dhpet wild animals
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "animal_id", nullable = false)
	public DhpetWildAnimals getDhpetWildAnimals() {
		return this.dhpetWildAnimals;
	}

	/**
	 * Sets the dhpet wild animals.
	 *
	 * @param dhpetWildAnimals the new dhpet wild animals
	 */
	public void setDhpetWildAnimals(DhpetWildAnimals dhpetWildAnimals) {
		this.dhpetWildAnimals = dhpetWildAnimals;
	}

	/**
	 * Gets the employee.
	 *
	 * @return the employee
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Sets the employee.
	 *
	 * @param employee the new employee
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	/**
	 * Gets the dhpet annual plan.
	 *
	 * @return the dhpet annual plan
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "annu_plan_id", nullable = false)
	public DhpetAnnualPlan getDhpetAnnualPlan() {
		return this.dhpetAnnualPlan;
	}

	/**
	 * Sets the dhpet annual plan.
	 *
	 * @param dhpetAnnualPlan the new dhpet annual plan
	 */
	public void setDhpetAnnualPlan(DhpetAnnualPlan dhpetAnnualPlan) {
		this.dhpetAnnualPlan = dhpetAnnualPlan;
	}

	/**
	 * Gets the date.
	 *
	 * @return the date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 13)
	public Date getDate() {
		return this.date;
	}

	/**
	 * Sets the date.
	 *
	 * @param date the new date
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * Gets the animals number.
	 *
	 * @return the animals number
	 */
	@Column(name = "animals_number", nullable = false)
	public Long getAnimalsNumber() {
		return this.animalsNumber;
	}

	/**
	 * Sets the animals number.
	 *
	 * @param animalsNumber the new animals number
	 */
	public void setAnimalsNumber(Long animalsNumber) {
		this.animalsNumber = animalsNumber;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * Gets the dhpet hunted animal details.
	 *
	 * @return the dhpet hunted animal details
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dhpetHuntedAnimals")
	public Set<DhpetHuntedAnimalDetail> getDhpetHuntedAnimalDetails() {
		return this.dhpetHuntedAnimalDetails;
	}

	/**
	 * Sets the dhpet hunted animal details.
	 *
	 * @param dhpetHuntedAnimalDetails the new dhpet hunted animal details
	 */
	public void setDhpetHuntedAnimalDetails(
			Set<DhpetHuntedAnimalDetail> dhpetHuntedAnimalDetails) {
		this.dhpetHuntedAnimalDetails = dhpetHuntedAnimalDetails;
	}

}
