package com.geoland.kfis.model;

// Generated Jan 27, 2016 3:36:50 PM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import org.hibernate.annotations.Type;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * DhpetTouristRegister generated by hbm2java.
 */
@Entity
@Table(name = "tdhpet_tourist_register", schema = "public")
public class DhpetTouristRegister extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The dhpet tourist purpose. */
	private DhpetTouristPurpose dhpetTouristPurpose;
	
	/** The employee. */
	private Employee employee;
	
	/** The dhpet location. */
	private DhpetLocation dhpetLocation;
	
	/** The start date. */
	private Date startDate;
	
	/** The end date. */
	private Date endDate;
	
	/** The payment. */
	private Double payment;
	
	/** The tourist number. */
	private Long touristNumber;
	
	/** The note. */
	private String note;
	
	/** The created date. */
	private Date createdDate;

	/**
	 * Instantiates a new dhpet tourist register.
	 */
	public DhpetTouristRegister() {
	}

	/**
	 * Instantiates a new dhpet tourist register.
	 *
	 * @param dhpetTouristPurpose the dhpet tourist purpose
	 * @param employee the employee
	 * @param dhpetLocation the dhpet location
	 * @param startDate the start date
	 * @param endDate the end date
	 * @param touristNumber the tourist number
	 * @param createdDate the created date
	 */
	public DhpetTouristRegister(DhpetTouristPurpose dhpetTouristPurpose,
			Employee employee, DhpetLocation dhpetLocation, Date startDate,
			Date endDate, Long touristNumber, Date createdDate) {
		this.dhpetTouristPurpose = dhpetTouristPurpose;
		this.employee = employee;
		this.dhpetLocation = dhpetLocation;
		this.startDate = startDate;
		this.endDate = endDate;
		this.touristNumber = touristNumber;
		this.createdDate = createdDate;
	}

	/**
	 * Instantiates a new dhpet tourist register.
	 *
	 * @param dhpetTouristPurpose the dhpet tourist purpose
	 * @param employee the employee
	 * @param dhpetLocation the dhpet location
	 * @param startDate the start date
	 * @param endDate the end date
	 * @param payment the payment
	 * @param touristNumber the tourist number
	 * @param note the note
	 * @param createdDate the created date
	 */
	public DhpetTouristRegister(DhpetTouristPurpose dhpetTouristPurpose,
			Employee employee, DhpetLocation dhpetLocation, Date startDate,
			Date endDate, Double payment, Long touristNumber, String note,
			Date createdDate) {
		this.dhpetTouristPurpose = dhpetTouristPurpose;
		this.employee = employee;
		this.dhpetLocation = dhpetLocation;
		this.startDate = startDate;
		this.endDate = endDate;
		this.payment = payment;
		this.touristNumber = touristNumber;
		this.note = note;
		this.createdDate = createdDate;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the dhpet tourist purpose.
	 *
	 * @return the dhpet tourist purpose
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "purpose_id", nullable = false)
	public DhpetTouristPurpose getDhpetTouristPurpose() {
		return this.dhpetTouristPurpose;
	}

	/**
	 * Sets the dhpet tourist purpose.
	 *
	 * @param dhpetTouristPurpose the new dhpet tourist purpose
	 */
	public void setDhpetTouristPurpose(DhpetTouristPurpose dhpetTouristPurpose) {
		this.dhpetTouristPurpose = dhpetTouristPurpose;
	}

	/**
	 * Gets the employee.
	 *
	 * @return the employee
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Sets the employee.
	 *
	 * @param employee the new employee
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	/**
	 * Gets the dhpet location.
	 *
	 * @return the dhpet location
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_id", nullable = false)
	public DhpetLocation getDhpetLocation() {
		return this.dhpetLocation;
	}

	/**
	 * Sets the dhpet location.
	 *
	 * @param dhpetLocation the new dhpet location
	 */
	public void setDhpetLocation(DhpetLocation dhpetLocation) {
		this.dhpetLocation = dhpetLocation;
	}

	/**
	 * Gets the start date.
	 *
	 * @return the start date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 13)
	public Date getStartDate() {
		return this.startDate;
	}

	/**
	 * Sets the start date.
	 *
	 * @param startDate the new start date
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * Gets the end date.
	 *
	 * @return the end date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 13)
	public Date getEndDate() {
		return this.endDate;
	}

	/**
	 * Sets the end date.
	 *
	 * @param endDate the new end date
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * Gets the payment.
	 *
	 * @return the payment
	 */
	@Column(name = "payment", precision = 17, scale = 17)
	public Double getPayment() {
		return this.payment;
	}

	/**
	 * Sets the payment.
	 *
	 * @param payment the new payment
	 */
	public void setPayment(Double payment) {
		this.payment = payment;
	}

	/**
	 * Gets the tourist number.
	 *
	 * @return the tourist number
	 */
	@Column(name = "tourist_number", nullable = false)
	public Long getTouristNumber() {
		return this.touristNumber;
	}

	/**
	 * Sets the tourist number.
	 *
	 * @param touristNumber the new tourist number
	 */
	public void setTouristNumber(Long touristNumber) {
		this.touristNumber = touristNumber;
	}

	/**
	 * Gets the note.
	 *
	 * @return the note
	 */
	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	/**
	 * Sets the note.
	 *
	 * @param note the new note
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
