package com.geoland.kfis.model;

// Generated Dec 15, 2015 8:50:06 AM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import org.hibernate.annotations.Type;
import com.geoland.kfis.persistence.hibernate.usertypes.Animalneeds;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * DhpetWildAnimalsRequest generated by hbm2java.
 */
@Entity
@Table(name = "tdhpet_wild_animals_request", schema = "public")
public class DhpetWildAnimalsRequest extends AbstractPersistentObject implements
		java.io.Serializable {

	/** The id. */
	private Long id;
	
	/** The dhpet wild animals. */
	private DhpetWildAnimals dhpetWildAnimals;
	
	/** The employee. */
	private Employee employee;
	
	/** The request for. */
	private Animalneeds requestFor;
	
	/** The max point. */
	private Double maxPoint;
	
	/** The created date. */
	private Date createdDate;
	
	/** The note. */
	private String note;

	/**
	 * Instantiates a new dhpet wild animals request.
	 */
	public DhpetWildAnimalsRequest() {
	}

	/**
	 * Instantiates a new dhpet wild animals request.
	 *
	 * @param dhpetWildAnimals the dhpet wild animals
	 * @param employee the employee
	 * @param requestFor the request for
	 * @param maxPoint the max point
	 * @param createdDate the created date
	 */
	public DhpetWildAnimalsRequest(DhpetWildAnimals dhpetWildAnimals,
			Employee employee, Animalneeds requestFor, Double maxPoint,
			Date createdDate) {
		this.dhpetWildAnimals = dhpetWildAnimals;
		this.employee = employee;
		this.requestFor = requestFor;
		this.maxPoint = maxPoint;
		this.createdDate = createdDate;
	}

	/**
	 * Instantiates a new dhpet wild animals request.
	 *
	 * @param dhpetWildAnimals the dhpet wild animals
	 * @param employee the employee
	 * @param requestFor the request for
	 * @param maxPoint the max point
	 * @param createdDate the created date
	 * @param note the note
	 */
	public DhpetWildAnimalsRequest(DhpetWildAnimals dhpetWildAnimals,
			Employee employee, Animalneeds requestFor, Double maxPoint,
			Date createdDate, String note) {
		this.dhpetWildAnimals = dhpetWildAnimals;
		this.employee = employee;
		this.requestFor = requestFor;
		this.maxPoint = maxPoint;
		this.createdDate = createdDate;
		this.note = note;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the dhpet wild animals.
	 *
	 * @return the dhpet wild animals
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "animal_id", nullable = false)
	public DhpetWildAnimals getDhpetWildAnimals() {
		return this.dhpetWildAnimals;
	}

	/**
	 * Sets the dhpet wild animals.
	 *
	 * @param dhpetWildAnimals the new dhpet wild animals
	 */
	public void setDhpetWildAnimals(DhpetWildAnimals dhpetWildAnimals) {
		this.dhpetWildAnimals = dhpetWildAnimals;
	}

	/**
	 * Gets the employee.
	 *
	 * @return the employee
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Sets the employee.
	 *
	 * @param employee the new employee
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	/**
	 * Gets the request for.
	 *
	 * @return the request for
	 */
	@Column(name = "request_for", nullable = false, length = 2)
	@Type(type = "com.geoland.kfis.persistence.hibernate.usertypes.AnimalneedsUserType")
	public Animalneeds getRequestFor() {
		return this.requestFor;
	}

	/**
	 * Sets the request for.
	 *
	 * @param requestFor the new request for
	 */
	public void setRequestFor(Animalneeds requestFor) {
		this.requestFor = requestFor;
	}

	/**
	 * Gets the max point.
	 *
	 * @return the max point
	 */
	@Column(name = "max_point", nullable = false, precision = 17, scale = 17)
	public Double getMaxPoint() {
		return this.maxPoint;
	}

	/**
	 * Sets the max point.
	 *
	 * @param maxPoint the new max point
	 */
	public void setMaxPoint(Double maxPoint) {
		this.maxPoint = maxPoint;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * Gets the note.
	 *
	 * @return the note
	 */
	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	/**
	 * Sets the note.
	 *
	 * @param note the new note
	 */
	public void setNote(String note) {
		this.note = note;
	}

}
