package com.geoland.kfis.model;

// Generated Feb 16, 2015 12:17:29 AM by Hibernate Tools 3.4.0.CR1

import com.geoland.framework.persistence.base.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * DpMngmtStatus generated by hbm2java.
 */
@Entity
@Table(name = "tdp_mngmt_status", schema = "public")
public class DpMngmtStatus extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The organisation by to dpt id. */
	private Organisation organisationByToDptId;
	
	/** The person by updatedby. */
	private Person personByUpdatedby;
	
	/** The person by createdby. */
	private Person personByCreatedby;
	
	/** The organisation by from dpt id. */
	private Organisation organisationByFromDptId;
	
	/** The dp mngmt. */
	private DpMngmt dpMngmt;
	
	/** The msg type. */
	private String msgType;
	
	/** The status code. */
	private String statusCode;
	
	/** The action taken. */
	private String actionTaken;
	
	/** The textmsg. */
	private String textmsg;
	
	/** The created. */
	private Date created;
	
	/** The updated. */
	private Date updated;
	
	/** The dp mngmts. */
	private Set<DpMngmt> dpMngmts = new HashSet<DpMngmt>(0);

	/**
	 * Instantiates a new dp mngmt status.
	 */
	public DpMngmtStatus() {
	}

	/**
	 * Instantiates a new dp mngmt status.
	 *
	 * @param personByUpdatedby the person by updatedby
	 * @param personByCreatedby the person by createdby
	 * @param dpMngmt the dp mngmt
	 * @param msgType the msg type
	 * @param statusCode the status code
	 * @param created the created
	 * @param updated the updated
	 */
	public DpMngmtStatus(Person personByUpdatedby, Person personByCreatedby,
			DpMngmt dpMngmt, String msgType, String statusCode, Date created,
			Date updated) {
		this.personByUpdatedby = personByUpdatedby;
		this.personByCreatedby = personByCreatedby;
		this.dpMngmt = dpMngmt;
		this.msgType = msgType;
		this.statusCode = statusCode;
		this.created = created;
		this.updated = updated;
	}

	/**
	 * Instantiates a new dp mngmt status.
	 *
	 * @param organisationByToDptId the organisation by to dpt id
	 * @param personByUpdatedby the person by updatedby
	 * @param personByCreatedby the person by createdby
	 * @param organisationByFromDptId the organisation by from dpt id
	 * @param dpMngmt the dp mngmt
	 * @param msgType the msg type
	 * @param statusCode the status code
	 * @param actionTaken the action taken
	 * @param textmsg the textmsg
	 * @param created the created
	 * @param updated the updated
	 * @param dpMngmts the dp mngmts
	 */
	public DpMngmtStatus(Organisation organisationByToDptId,
			Person personByUpdatedby, Person personByCreatedby,
			Organisation organisationByFromDptId, DpMngmt dpMngmt,
			String msgType, String statusCode, String actionTaken,
			String textmsg, Date created, Date updated, Set<DpMngmt> dpMngmts) {
		this.organisationByToDptId = organisationByToDptId;
		this.personByUpdatedby = personByUpdatedby;
		this.personByCreatedby = personByCreatedby;
		this.organisationByFromDptId = organisationByFromDptId;
		this.dpMngmt = dpMngmt;
		this.msgType = msgType;
		this.statusCode = statusCode;
		this.actionTaken = actionTaken;
		this.textmsg = textmsg;
		this.created = created;
		this.updated = updated;
		this.dpMngmts = dpMngmts;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the organisation by to dpt id.
	 *
	 * @return the organisation by to dpt id
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to_dpt_id")
	public Organisation getOrganisationByToDptId() {
		return this.organisationByToDptId;
	}

	/**
	 * Sets the organisation by to dpt id.
	 *
	 * @param organisationByToDptId the new organisation by to dpt id
	 */
	public void setOrganisationByToDptId(Organisation organisationByToDptId) {
		this.organisationByToDptId = organisationByToDptId;
	}

	/**
	 * Gets the person by updatedby.
	 *
	 * @return the person by updatedby
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedby", nullable = false)
	public Person getPersonByUpdatedby() {
		return this.personByUpdatedby;
	}

	/**
	 * Sets the person by updatedby.
	 *
	 * @param personByUpdatedby the new person by updatedby
	 */
	public void setPersonByUpdatedby(Person personByUpdatedby) {
		this.personByUpdatedby = personByUpdatedby;
	}

	/**
	 * Gets the person by createdby.
	 *
	 * @return the person by createdby
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "createdby", nullable = false)
	public Person getPersonByCreatedby() {
		return this.personByCreatedby;
	}

	/**
	 * Sets the person by createdby.
	 *
	 * @param personByCreatedby the new person by createdby
	 */
	public void setPersonByCreatedby(Person personByCreatedby) {
		this.personByCreatedby = personByCreatedby;
	}

	/**
	 * Gets the organisation by from dpt id.
	 *
	 * @return the organisation by from dpt id
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from_dpt_id")
	public Organisation getOrganisationByFromDptId() {
		return this.organisationByFromDptId;
	}

	/**
	 * Sets the organisation by from dpt id.
	 *
	 * @param organisationByFromDptId the new organisation by from dpt id
	 */
	public void setOrganisationByFromDptId(Organisation organisationByFromDptId) {
		this.organisationByFromDptId = organisationByFromDptId;
	}

	/**
	 * Gets the dp mngmt.
	 *
	 * @return the dp mngmt
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dp_mngm_id", nullable = false)
	public DpMngmt getDpMngmt() {
		return this.dpMngmt;
	}

	/**
	 * Sets the dp mngmt.
	 *
	 * @param dpMngmt the new dp mngmt
	 */
	public void setDpMngmt(DpMngmt dpMngmt) {
		this.dpMngmt = dpMngmt;
	}

	/**
	 * Gets the msg type.
	 *
	 * @return the msg type
	 */
	@Column(name = "msg_type", nullable = false, length = 1)
	public String getMsgType() {
		return this.msgType;
	}

	/**
	 * Sets the msg type.
	 *
	 * @param msgType the new msg type
	 */
	public void setMsgType(String msgType) {
		this.msgType = msgType;
	}

	/**
	 * Gets the status code.
	 *
	 * @return the status code
	 */
	@Column(name = "status_code", nullable = false, length = 20)
	public String getStatusCode() {
		return this.statusCode;
	}

	/**
	 * Sets the status code.
	 *
	 * @param statusCode the new status code
	 */
	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	/**
	 * Gets the action taken.
	 *
	 * @return the action taken
	 */
	@Column(name = "action_taken")
	public String getActionTaken() {
		return this.actionTaken;
	}

	/**
	 * Sets the action taken.
	 *
	 * @param actionTaken the new action taken
	 */
	public void setActionTaken(String actionTaken) {
		this.actionTaken = actionTaken;
	}

	/**
	 * Gets the textmsg.
	 *
	 * @return the textmsg
	 */
	@Column(name = "textmsg", length = 2000)
	public String getTextmsg() {
		return this.textmsg;
	}

	/**
	 * Sets the textmsg.
	 *
	 * @param textmsg the new textmsg
	 */
	public void setTextmsg(String textmsg) {
		this.textmsg = textmsg;
	}

	/**
	 * Gets the created.
	 *
	 * @return the created
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	/**
	 * Sets the created.
	 *
	 * @param created the new created
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * Gets the updated.
	 *
	 * @return the updated
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	/**
	 * Sets the updated.
	 *
	 * @param updated the new updated
	 */
	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	/**
	 * Gets the dp mngmts.
	 *
	 * @return the dp mngmts
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dpMngmtStatus")
	public Set<DpMngmt> getDpMngmts() {
		return this.dpMngmts;
	}

	/**
	 * Sets the dp mngmts.
	 *
	 * @param dpMngmts the new dp mngmts
	 */
	public void setDpMngmts(Set<DpMngmt> dpMngmts) {
		this.dpMngmts = dpMngmts;
	}

}
