package com.geoland.kfis.model;
// Generated 11.06.2020 23:02:56 by Hibernate Tools 5.2.11.Final

import com.geoland.framework.persistence.base.*;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * EmployeeSalaryTaxRates generated by hbm2java
 */
@Entity
@Table(name = "thrm_employee_salary_tax_rates", schema = "public")
public class EmployeeSalaryTaxRates extends AbstractPersistentObject implements java.io.Serializable {

	private Long id;
	private Person createdBy;
	private String taxNormName;
	private BigDecimal percentage;
	private BigDecimal startAmount;
	private BigDecimal endAmount;
	private Date validDateFrom;
	private Date validDateTo;
	private boolean valid;
	private String note;
	private Date createdDate;

	public EmployeeSalaryTaxRates() {
	}

	public EmployeeSalaryTaxRates(Person createdBy, String taxNormName, BigDecimal percentage, BigDecimal startAmount,
			BigDecimal endAmount, Date validDateFrom, Date validDateTo, boolean valid, Date createdDate) {
		this.createdBy = createdBy;
		this.taxNormName = taxNormName;
		this.percentage = percentage;
		this.startAmount = startAmount;
		this.endAmount = endAmount;
		this.validDateFrom = validDateFrom;
		this.validDateTo = validDateTo;
		this.valid = valid;
		this.createdDate = createdDate;
	}

	public EmployeeSalaryTaxRates(Person createdBy, String taxNormName, BigDecimal percentage, BigDecimal startAmount,
			BigDecimal endAmount, Date validDateFrom, Date validDateTo, boolean valid, String note, Date createdDate) {
		this.createdBy = createdBy;
		this.taxNormName = taxNormName;
		this.percentage = percentage;
		this.startAmount = startAmount;
		this.endAmount = endAmount;
		this.validDateFrom = validDateFrom;
		this.validDateTo = validDateTo;
		this.valid = valid;
		this.note = note;
		this.createdDate = createdDate;
	}

	@GenericGenerator(name = "com.geoland.kfis.model.EmployeeSalaryTaxRatesIdGenerator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "com.geoland.kfis.model.EmployeeSalaryTaxRatesIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Person getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Person createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "tax_norm_name", nullable = false, length = 30)
	public String getTaxNormName() {
		return this.taxNormName;
	}

	public void setTaxNormName(String taxNormName) {
		this.taxNormName = taxNormName;
	}

	@Column(name = "percentage", nullable = false, precision = 3)
	public BigDecimal getPercentage() {
		return this.percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	@Column(name = "start_amount", nullable = false, precision = 8)
	public BigDecimal getStartAmount() {
		return this.startAmount;
	}

	public void setStartAmount(BigDecimal startAmount) {
		this.startAmount = startAmount;
	}

	@Column(name = "end_amount", nullable = false, precision = 8)
	public BigDecimal getEndAmount() {
		return this.endAmount;
	}

	public void setEndAmount(BigDecimal endAmount) {
		this.endAmount = endAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_date_from", nullable = false, length = 13)
	public Date getValidDateFrom() {
		return this.validDateFrom;
	}

	public void setValidDateFrom(Date validDateFrom) {
		this.validDateFrom = validDateFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "valid_date_to", nullable = false, length = 13)
	public Date getValidDateTo() {
		return this.validDateTo;
	}

	public void setValidDateTo(Date validDateTo) {
		this.validDateTo = validDateTo;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
