package com.geoland.kfis.model;

// Generated Feb 11, 2015 2:26:59 AM by Hibernate Tools 3.4.0.CR1

import com.geoland.framework.persistence.base.*;
import org.hibernate.annotations.Type;
import com.geoland.kfis.persistence.hibernate.usertypes.Education;
import com.geoland.kfis.persistence.hibernate.usertypes.Skill;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * EmployeeSkill generated by hbm2java.
 */
@Entity
@Table(name = "thrm_employee_skill", schema = "public")
public class EmployeeSkill extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The party. */
	private Party party;
	
	/** The employee. */
	private Employee employee;
	
	/** The skill type. */
	private Skill skillType;
	
	/** The education type. */
	private Education educationType;
	
	/** The skill name. */
	private String skillName;
	
	/** The institute. */
	private String institute;
	
	/** The date start. */
	private Date dateStart;
	
	/** The date end. */
	private Date dateEnd;
	
	/** The details. */
	private String details;
	
	/** The doc type. */
	private String docType;
	
	/** The doc name. */
	private String docName;
	
	/** The doc size. */
	private Long docSize;
	
	/** The doc. */
	private byte[] doc;
	
	/** The note. */
	private String note;
	
	/** The created date. */
	private Date createdDate;

	/**
	 * Instantiates a new employee skill.
	 */
	public EmployeeSkill() {
	}

	/**
	 * Instantiates a new employee skill.
	 *
	 * @param party the party
	 * @param employee the employee
	 * @param skillType the skill type
	 * @param createdDate the created date
	 */
	public EmployeeSkill(Party party, Employee employee, Skill skillType,
			Date createdDate) {
		this.party = party;
		this.employee = employee;
		this.skillType = skillType;
		this.createdDate = createdDate;
	}

	/**
	 * Instantiates a new employee skill.
	 *
	 * @param party the party
	 * @param employee the employee
	 * @param skillType the skill type
	 * @param educationType the education type
	 * @param skillName the skill name
	 * @param institute the institute
	 * @param dateStart the date start
	 * @param dateEnd the date end
	 * @param details the details
	 * @param docType the doc type
	 * @param docName the doc name
	 * @param docSize the doc size
	 * @param doc the doc
	 * @param note the note
	 * @param createdDate the created date
	 */
	public EmployeeSkill(Party party, Employee employee, Skill skillType,
			Education educationType, String skillName, String institute,
			Date dateStart, Date dateEnd, String details, String docType,
			String docName, Long docSize, byte[] doc, String note,
			Date createdDate) {
		this.party = party;
		this.employee = employee;
		this.skillType = skillType;
		this.educationType = educationType;
		this.skillName = skillName;
		this.institute = institute;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.details = details;
		this.docType = docType;
		this.docName = docName;
		this.docSize = docSize;
		this.doc = doc;
		this.note = note;
		this.createdDate = createdDate;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the party.
	 *
	 * @return the party
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Party getParty() {
		return this.party;
	}

	/**
	 * Sets the party.
	 *
	 * @param party the new party
	 */
	public void setParty(Party party) {
		this.party = party;
	}

	/**
	 * Gets the employee.
	 *
	 * @return the employee
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Sets the employee.
	 *
	 * @param employee the new employee
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	/**
	 * Gets the skill type.
	 *
	 * @return the skill type
	 */
	@Column(name = "skill_type", nullable = false, length = 1)
	@Type(type = "com.geoland.kfis.persistence.hibernate.usertypes.SkillUserType")
	public Skill getSkillType() {
		return this.skillType;
	}

	/**
	 * Sets the skill type.
	 *
	 * @param skillType the new skill type
	 */
	public void setSkillType(Skill skillType) {
		this.skillType = skillType;
	}

	/**
	 * Gets the education type.
	 *
	 * @return the education type
	 */
	@Column(name = "education_type", length = 2)
	@Type(type = "com.geoland.kfis.persistence.hibernate.usertypes.EducationUserType")
	public Education getEducationType() {
		return this.educationType;
	}

	/**
	 * Sets the education type.
	 *
	 * @param educationType the new education type
	 */
	public void setEducationType(Education educationType) {
		this.educationType = educationType;
	}

	/**
	 * Gets the skill name.
	 *
	 * @return the skill name
	 */
	@Column(name = "skill_name", length = 20)
	public String getSkillName() {
		return this.skillName;
	}

	/**
	 * Sets the skill name.
	 *
	 * @param skillName the new skill name
	 */
	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	/**
	 * Gets the institute.
	 *
	 * @return the institute
	 */
	@Column(name = "institute", length = 400)
	public String getInstitute() {
		return this.institute;
	}

	/**
	 * Sets the institute.
	 *
	 * @param institute the new institute
	 */
	public void setInstitute(String institute) {
		this.institute = institute;
	}

	/**
	 * Gets the date start.
	 *
	 * @return the date start
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "date_start", length = 13)
	public Date getDateStart() {
		return this.dateStart;
	}

	/**
	 * Sets the date start.
	 *
	 * @param dateStart the new date start
	 */
	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	/**
	 * Gets the date end.
	 *
	 * @return the date end
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "date_end", length = 13)
	public Date getDateEnd() {
		return this.dateEnd;
	}

	/**
	 * Sets the date end.
	 *
	 * @param dateEnd the new date end
	 */
	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	/**
	 * Gets the details.
	 *
	 * @return the details
	 */
	@Column(name = "details", length = 400)
	public String getDetails() {
		return this.details;
	}

	/**
	 * Sets the details.
	 *
	 * @param details the new details
	 */
	public void setDetails(String details) {
		this.details = details;
	}

	/**
	 * Gets the doc type.
	 *
	 * @return the doc type
	 */
	@Column(name = "doc_type", length = 100)
	public String getDocType() {
		return this.docType;
	}

	/**
	 * Sets the doc type.
	 *
	 * @param docType the new doc type
	 */
	public void setDocType(String docType) {
		this.docType = docType;
	}

	/**
	 * Gets the doc name.
	 *
	 * @return the doc name
	 */
	@Column(name = "doc_name", length = 100)
	public String getDocName() {
		return this.docName;
	}

	/**
	 * Sets the doc name.
	 *
	 * @param docName the new doc name
	 */
	public void setDocName(String docName) {
		this.docName = docName;
	}

	/**
	 * Gets the doc size.
	 *
	 * @return the doc size
	 */
	@Column(name = "doc_size")
	public Long getDocSize() {
		return this.docSize;
	}

	/**
	 * Sets the doc size.
	 *
	 * @param docSize the new doc size
	 */
	public void setDocSize(Long docSize) {
		this.docSize = docSize;
	}

	/**
	 * Gets the doc.
	 *
	 * @return the doc
	 */
	@Column(name = "doc")
	public byte[] getDoc() {
		return this.doc;
	}

	/**
	 * Sets the doc.
	 *
	 * @param doc the new doc
	 */
	public void setDoc(byte[] doc) {
		this.doc = doc;
	}

	/**
	 * Gets the note.
	 *
	 * @return the note
	 */
	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	/**
	 * Sets the note.
	 *
	 * @param note the new note
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
