package com.geoland.kfis.model;
// Generated 11.06.2020 23:02:56 by Hibernate Tools 5.2.11.Final

import com.geoland.framework.persistence.base.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * EmployeeSalary generated by hbm2java
 */
@Entity
@Table(name = "thrm_employee_salary", schema = "public")
public class EmployeeSalary extends AbstractPersistentObject implements java.io.Serializable {

	private Long id;
	private Employee employee;
	private Person createdBy;
	private BigDecimal grosssalary;
	private BigDecimal basicsalary;
	private Long regularworkhours;
	private Character payperiod;
	private boolean autopay;
	private Date createdDate;
	private Set<EmployeeSalaryPayroll> employeeSalaryPayrolls = new HashSet<EmployeeSalaryPayroll>(0);
	private Set<EmployeeSalaryAdjustment> employeeSalaryAdjustments = new HashSet<EmployeeSalaryAdjustment>(0);

	public EmployeeSalary() {
	}

	public EmployeeSalary(Employee employee, Person createdBy, Character payperiod, boolean autopay, Date createdDate) {
		this.employee = employee;
		this.createdBy = createdBy;
		this.payperiod = payperiod;
		this.autopay = autopay;
		this.createdDate = createdDate;
	}

	public EmployeeSalary(Employee employee, Person createdBy, BigDecimal grosssalary, BigDecimal basicsalary,
			Long regularworkhours, Character payperiod, boolean autopay, Date createdDate,
			Set<EmployeeSalaryPayroll> employeeSalaryPayrolls,
			Set<EmployeeSalaryAdjustment> employeeSalaryAdjustments) {
		this.employee = employee;
		this.createdBy = createdBy;
		this.grosssalary = grosssalary;
		this.basicsalary = basicsalary;
		this.regularworkhours = regularworkhours;
		this.payperiod = payperiod;
		this.autopay = autopay;
		this.createdDate = createdDate;
		this.employeeSalaryPayrolls = employeeSalaryPayrolls;
		this.employeeSalaryAdjustments = employeeSalaryAdjustments;
	}

	@GenericGenerator(name = "com.geoland.kfis.model.EmployeeSalaryIdGenerator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "com.geoland.kfis.model.EmployeeSalaryIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Person getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Person createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "grosssalary", precision = 8)
	public BigDecimal getGrosssalary() {
		return this.grosssalary;
	}

	public void setGrosssalary(BigDecimal grosssalary) {
		this.grosssalary = grosssalary;
	}

	@Column(name = "basicsalary", precision = 8)
	public BigDecimal getBasicsalary() {
		return this.basicsalary;
	}

	public void setBasicsalary(BigDecimal basicsalary) {
		this.basicsalary = basicsalary;
	}

	@Column(name = "regularworkhours")
	public Long getRegularworkhours() {
		return this.regularworkhours;
	}

	public void setRegularworkhours(Long regularworkhours) {
		this.regularworkhours = regularworkhours;
	}

	@Column(name = "payperiod", nullable = false, length = 1)
	public Character getPayperiod() {
		return this.payperiod;
	}

	public void setPayperiod(Character payperiod) {
		this.payperiod = payperiod;
	}

	@Column(name = "autopay", nullable = false)
	public boolean isAutopay() {
		return this.autopay;
	}

	public void setAutopay(boolean autopay) {
		this.autopay = autopay;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeSalary")
	public Set<EmployeeSalaryPayroll> getEmployeeSalaryPayrolls() {
		return this.employeeSalaryPayrolls;
	}

	public void setEmployeeSalaryPayrolls(Set<EmployeeSalaryPayroll> employeeSalaryPayrolls) {
		this.employeeSalaryPayrolls = employeeSalaryPayrolls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employeeSalary")
	public Set<EmployeeSalaryAdjustment> getEmployeeSalaryAdjustments() {
		return this.employeeSalaryAdjustments;
	}

	public void setEmployeeSalaryAdjustments(Set<EmployeeSalaryAdjustment> employeeSalaryAdjustments) {
		this.employeeSalaryAdjustments = employeeSalaryAdjustments;
	}

}
