package com.geoland.kfis.model;
// Generated 07.05.2020 13:43:57 by Hibernate Tools 5.2.11.Final

import com.geoland.framework.persistence.base.*;
import com.geoland.kfis.persistence.hibernate.usertypes.Month;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * FinancialInput generated by hbm2java
 */
@Entity
@Table(name = "tfin_input", schema = "public")
public class FinancialInput extends AbstractPersistentObject implements java.io.Serializable {

	private Long id;
	private FinInputStatus finInputStatus;
	private FinancialType financialType;
	private Employee employee;
	private Organisation organisation;
	private Long year;
	private Month month;
	private BigDecimal cumulativeValue;
	private boolean allocated;
	private Date allocatedDate;
	private Date createdTime;
	private Date inputDate;
	private Set<FinInputStatus> finInputStatuses = new HashSet<FinInputStatus>(0);

	public FinancialInput() {
	}

	public FinancialInput(FinancialType financialType, Employee employee, Organisation organisation, Long year,
			Month month, boolean allocated, Date createdTime, Date inputDate) {
		this.financialType = financialType;
		this.employee = employee;
		this.organisation = organisation;
		this.year = year;
		this.month = month;
		this.allocated = allocated;
		this.createdTime = createdTime;
		this.inputDate = inputDate;
	}

	public FinancialInput(FinInputStatus finInputStatus, FinancialType financialType, Employee employee,
			Organisation organisation, Long year, Month month, BigDecimal cumulativeValue, boolean allocated,
			Date allocatedDate, Date createdTime, Date inputDate, Set<FinInputStatus> finInputStatuses) {
		this.finInputStatus = finInputStatus;
		this.financialType = financialType;
		this.employee = employee;
		this.organisation = organisation;
		this.year = year;
		this.month = month;
		this.cumulativeValue = cumulativeValue;
		this.allocated = allocated;
		this.allocatedDate = allocatedDate;
		this.createdTime = createdTime;
		this.inputDate = inputDate;
		this.finInputStatuses = finInputStatuses;
	}

	@GenericGenerator(name = "com.geoland.kfis.model.FinancialInputIdGenerator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "com.geoland.kfis.model.FinancialInputIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "current_status")
	public FinInputStatus getFinInputStatus() {
		return this.finInputStatus;
	}

	public void setFinInputStatus(FinInputStatus finInputStatus) {
		this.finInputStatus = finInputStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "input_type_id", nullable = false)
	public FinancialType getFinancialType() {
		return this.financialType;
	}

	public void setFinancialType(FinancialType financialType) {
		this.financialType = financialType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "municipality_id", nullable = false)
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@Column(name = "year", nullable = false)
	public Long getYear() {
		return this.year;
	}

	public void setYear(Long year) {
		this.year = year;
	}

	@Column(name = "month", nullable = false, length = 2)

	@Type(type = "com.geoland.kfis.persistence.hibernate.usertypes.MonthUserType")
	public Month getMonth() {
		return this.month;
	}

	public void setMonth(Month month) {
		this.month = month;
	}

	@Column(name = "cumulative_value", precision = 10)
	public BigDecimal getCumulativeValue() {
		return this.cumulativeValue;
	}

	public void setCumulativeValue(BigDecimal cumulativeValue) {
		this.cumulativeValue = cumulativeValue;
	}

	@Column(name = "allocated", nullable = false)
	public boolean isAllocated() {
		return this.allocated;
	}

	public void setAllocated(boolean allocated) {
		this.allocated = allocated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "allocated_date", length = 13)
	public Date getAllocatedDate() {
		return this.allocatedDate;
	}

	public void setAllocatedDate(Date allocatedDate) {
		this.allocatedDate = allocatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 29)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "input_date", nullable = false, length = 13)
	public Date getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "financialInput")
	public Set<FinInputStatus> getFinInputStatuses() {
		return this.finInputStatuses;
	}

	public void setFinInputStatuses(Set<FinInputStatus> finInputStatuses) {
		this.finInputStatuses = finInputStatuses;
	}

}
