package com.geoland.kfis.model;
// Generated 07.05.2020 13:43:57 by Hibernate Tools 5.2.11.Final

import com.geoland.framework.persistence.base.*;
import com.geoland.kfis.persistence.hibernate.usertypes.Finoutputtype;
import com.geoland.kfis.persistence.hibernate.usertypes.Month;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * FinancialOutput generated by hbm2java
 */
@Entity
@Table(name = "tfin_output", schema = "public")
public class FinancialOutput extends AbstractPersistentObject implements java.io.Serializable {

	private Long id;
	private FinancialType financialType;
	private Employee employee;
	private Organisation organisation;
	private String uopNumber;
	private Long freeBalance;
	private Date dateOfCommitment;
	private String economicCode;
	private String descriptionOfEconomicCode;
	private Double valueInEuro;
	private String descriptionCpo;
	private Long souceFund;
	private String beneficiary;
	private String nrbCode;
	private String invoiceNumber;
	private Date paymentDate;
	private Month month;
	private Finoutputtype outputType;
	private Date createdTime;

	public FinancialOutput() {
	}

	public FinancialOutput(Employee employee, String uopNumber, Long freeBalance, String economicCode,
			Double valueInEuro, Finoutputtype outputType, Date createdTime) {
		this.employee = employee;
		this.uopNumber = uopNumber;
		this.freeBalance = freeBalance;
		this.economicCode = economicCode;
		this.valueInEuro = valueInEuro;
		this.outputType = outputType;
		this.createdTime = createdTime;
	}

	public FinancialOutput(FinancialType financialType, Employee employee, Organisation organisation, String uopNumber,
			Long freeBalance, Date dateOfCommitment, String economicCode, String descriptionOfEconomicCode,
			Double valueInEuro, String descriptionCpo, Long souceFund, String beneficiary, String nrbCode,
			String invoiceNumber, Date paymentDate, Month month, Finoutputtype outputType, Date createdTime) {
		this.financialType = financialType;
		this.employee = employee;
		this.organisation = organisation;
		this.uopNumber = uopNumber;
		this.freeBalance = freeBalance;
		this.dateOfCommitment = dateOfCommitment;
		this.economicCode = economicCode;
		this.descriptionOfEconomicCode = descriptionOfEconomicCode;
		this.valueInEuro = valueInEuro;
		this.descriptionCpo = descriptionCpo;
		this.souceFund = souceFund;
		this.beneficiary = beneficiary;
		this.nrbCode = nrbCode;
		this.invoiceNumber = invoiceNumber;
		this.paymentDate = paymentDate;
		this.month = month;
		this.outputType = outputType;
		this.createdTime = createdTime;
	}

	@GenericGenerator(name = "com.geoland.kfis.model.FinancialOutputIdGenerator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "com.geoland.kfis.model.FinancialOutputIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expenditure_type")
	public FinancialType getFinancialType() {
		return this.financialType;
	}

	public void setFinancialType(FinancialType financialType) {
		this.financialType = financialType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "department")
	public Organisation getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	@Column(name = "uop_number", nullable = false, length = 50)
	public String getUopNumber() {
		return this.uopNumber;
	}

	public void setUopNumber(String uopNumber) {
		this.uopNumber = uopNumber;
	}

	@Column(name = "free_balance", nullable = false)
	public Long getFreeBalance() {
		return this.freeBalance;
	}

	public void setFreeBalance(Long freeBalance) {
		this.freeBalance = freeBalance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_commitment", length = 13)
	public Date getDateOfCommitment() {
		return this.dateOfCommitment;
	}

	public void setDateOfCommitment(Date dateOfCommitment) {
		this.dateOfCommitment = dateOfCommitment;
	}

	@Column(name = "economic_code", nullable = false, length = 100)
	public String getEconomicCode() {
		return this.economicCode;
	}

	public void setEconomicCode(String economicCode) {
		this.economicCode = economicCode;
	}

	@Column(name = "description_of_economic_code")
	public String getDescriptionOfEconomicCode() {
		return this.descriptionOfEconomicCode;
	}

	public void setDescriptionOfEconomicCode(String descriptionOfEconomicCode) {
		this.descriptionOfEconomicCode = descriptionOfEconomicCode;
	}

	@Column(name = "value_in_euro", nullable = false, precision = 17, scale = 17)
	public Double getValueInEuro() {
		return this.valueInEuro;
	}

	public void setValueInEuro(Double valueInEuro) {
		this.valueInEuro = valueInEuro;
	}

	@Column(name = "description_cpo")
	public String getDescriptionCpo() {
		return this.descriptionCpo;
	}

	public void setDescriptionCpo(String descriptionCpo) {
		this.descriptionCpo = descriptionCpo;
	}

	@Column(name = "souce_fund")
	public Long getSouceFund() {
		return this.souceFund;
	}

	public void setSouceFund(Long souceFund) {
		this.souceFund = souceFund;
	}

	@Column(name = "beneficiary", length = 100)
	public String getBeneficiary() {
		return this.beneficiary;
	}

	public void setBeneficiary(String beneficiary) {
		this.beneficiary = beneficiary;
	}

	@Column(name = "nrb_code", length = 100)
	public String getNrbCode() {
		return this.nrbCode;
	}

	public void setNrbCode(String nrbCode) {
		this.nrbCode = nrbCode;
	}

	@Column(name = "invoice_number", length = 100)
	public String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "payment_date", length = 13)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "month", length = 2)

	@Type(type = "com.geoland.kfis.persistence.hibernate.usertypes.MonthUserType")
	public Month getMonth() {
		return this.month;
	}

	public void setMonth(Month month) {
		this.month = month;
	}

	@Column(name = "output_type", nullable = false, length = 2)

	@Type(type = "com.geoland.kfis.persistence.hibernate.usertypes.FinoutputtypeUserType")
	public Finoutputtype getOutputType() {
		return this.outputType;
	}

	public void setOutputType(Finoutputtype outputType) {
		this.outputType = outputType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 29)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
