package com.geoland.kfis.model;
// Generated 07.05.2020 13:36:25 by Hibernate Tools 5.2.11.Final

import com.geoland.framework.persistence.base.*;
import com.geoland.kfis.persistence.hibernate.usertypes.Fininputstatus;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * FinInputStatus generated by hbm2java
 */
@Entity
@Table(name = "tfin_input_status", schema = "public")
public class FinInputStatus extends AbstractPersistentObject implements java.io.Serializable {

	private Long id;
	private FinancialInput financialInput;
	private Employee employee;
	private Fininputstatus status;
	private String docType;
	private String docName;
	private Long docSize;
	private byte[] doc;
	private String note;
	private Date createDate;
	private Set<FinancialInput> financialInputs = new HashSet<FinancialInput>(0);

	public FinInputStatus() {
	}

	public FinInputStatus(FinancialInput financialInput, Employee employee, Fininputstatus status, Date createDate) {
		this.financialInput = financialInput;
		this.employee = employee;
		this.status = status;
		this.createDate = createDate;
	}

	public FinInputStatus(FinancialInput financialInput, Employee employee, Fininputstatus status, String docType,
			String docName, Long docSize, byte[] doc, String note, Date createDate,
			Set<FinancialInput> financialInputs) {
		this.financialInput = financialInput;
		this.employee = employee;
		this.status = status;
		this.docType = docType;
		this.docName = docName;
		this.docSize = docSize;
		this.doc = doc;
		this.note = note;
		this.createDate = createDate;
		this.financialInputs = financialInputs;
	}

	@GenericGenerator(name = "com.geoland.kfis.model.FinInputStatusIdGenerator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "com.geoland.kfis.model.FinInputStatusIdGenerator")

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "input_id", nullable = false)
	public FinancialInput getFinancialInput() {
		return this.financialInput;
	}

	public void setFinancialInput(FinancialInput financialInput) {
		this.financialInput = financialInput;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "create_by", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "status", nullable = false, length = 2)

	@Type(type = "com.geoland.kfis.persistence.hibernate.usertypes.FininputstatusUserType")
	public Fininputstatus getStatus() {
		return this.status;
	}

	public void setStatus(Fininputstatus status) {
		this.status = status;
	}

	@Column(name = "doc_type", length = 100)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Column(name = "doc_name", length = 100)
	public String getDocName() {
		return this.docName;
	}

	public void setDocName(String docName) {
		this.docName = docName;
	}

	@Column(name = "doc_size")
	public Long getDocSize() {
		return this.docSize;
	}

	public void setDocSize(Long docSize) {
		this.docSize = docSize;
	}

	@Column(name = "doc")
	public byte[] getDoc() {
		return this.doc;
	}

	public void setDoc(byte[] doc) {
		this.doc = doc;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 29)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "finInputStatus")
	public Set<FinancialInput> getFinancialInputs() {
		return this.financialInputs;
	}

	public void setFinancialInputs(Set<FinancialInput> financialInputs) {
		this.financialInputs = financialInputs;
	}

}
