package com.geoland.kfis.model;

// Generated Jun 11, 2015 9:39:14 AM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * HrmAnnualPlan generated by hbm2java.
 */
@Entity
@Table(name = "thrm_annual_plan", schema = "public")
public class HrmAnnualPlan extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The hrm annual plan status. */
	private HrmAnnualPlanStatus hrmAnnualPlanStatus;
	
	/** The annual plan al. */
	private String annualPlanAl;
	
	/** The annual plan en. */
	private String annualPlanEn;
	
	/** The annual plan sr. */
	private String annualPlanSr;
	
	/** The submission date. */
	private Date submissionDate;
	
	/** The comment. */
	private String comment;
	
	/** The hrm ann plan employees. */
	private Set<HrmAnnPlanEmployee> hrmAnnPlanEmployees = new HashSet<HrmAnnPlanEmployee>(
			0);
	
	/** The hrm annual plan docs. */
	private Set<HrmAnnualPlanDoc> hrmAnnualPlanDocs = new HashSet<HrmAnnualPlanDoc>(
			0);
	
	/** The hrm annual plan statuses. */
	private Set<HrmAnnualPlanStatus> hrmAnnualPlanStatuses = new HashSet<HrmAnnualPlanStatus>(
			0);

	/**
	 * Instantiates a new hrm annual plan.
	 */
	public HrmAnnualPlan() {
	}

	/**
	 * Instantiates a new hrm annual plan.
	 *
	 * @param annualPlanAl the annual plan al
	 * @param annualPlanEn the annual plan en
	 * @param annualPlanSr the annual plan sr
	 */
	public HrmAnnualPlan(String annualPlanAl, String annualPlanEn,
			String annualPlanSr) {
		this.annualPlanAl = annualPlanAl;
		this.annualPlanEn = annualPlanEn;
		this.annualPlanSr = annualPlanSr;
	}

	/**
	 * Instantiates a new hrm annual plan.
	 *
	 * @param hrmAnnualPlanStatus the hrm annual plan status
	 * @param annualPlanAl the annual plan al
	 * @param annualPlanEn the annual plan en
	 * @param annualPlanSr the annual plan sr
	 * @param submissionDate the submission date
	 * @param comment the comment
	 * @param hrmAnnPlanEmployees the hrm ann plan employees
	 * @param hrmAnnualPlanDocs the hrm annual plan docs
	 * @param hrmAnnualPlanStatuses the hrm annual plan statuses
	 */
	public HrmAnnualPlan(HrmAnnualPlanStatus hrmAnnualPlanStatus,
			String annualPlanAl, String annualPlanEn, String annualPlanSr,
			Date submissionDate, String comment,
			Set<HrmAnnPlanEmployee> hrmAnnPlanEmployees,
			Set<HrmAnnualPlanDoc> hrmAnnualPlanDocs,
			Set<HrmAnnualPlanStatus> hrmAnnualPlanStatuses) {
		this.hrmAnnualPlanStatus = hrmAnnualPlanStatus;
		this.annualPlanAl = annualPlanAl;
		this.annualPlanEn = annualPlanEn;
		this.annualPlanSr = annualPlanSr;
		this.submissionDate = submissionDate;
		this.comment = comment;
		this.hrmAnnPlanEmployees = hrmAnnPlanEmployees;
		this.hrmAnnualPlanDocs = hrmAnnualPlanDocs;
		this.hrmAnnualPlanStatuses = hrmAnnualPlanStatuses;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the hrm annual plan status.
	 *
	 * @return the hrm annual plan status
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "current_status")
	public HrmAnnualPlanStatus getHrmAnnualPlanStatus() {
		return this.hrmAnnualPlanStatus;
	}

	/**
	 * Sets the hrm annual plan status.
	 *
	 * @param hrmAnnualPlanStatus the new hrm annual plan status
	 */
	public void setHrmAnnualPlanStatus(HrmAnnualPlanStatus hrmAnnualPlanStatus) {
		this.hrmAnnualPlanStatus = hrmAnnualPlanStatus;
	}

	/**
	 * Gets the annual plan al.
	 *
	 * @return the annual plan al
	 */
	@Column(name = "annual_plan_al", nullable = false, length = 50)
	public String getAnnualPlanAl() {
		return this.annualPlanAl;
	}

	/**
	 * Sets the annual plan al.
	 *
	 * @param annualPlanAl the new annual plan al
	 */
	public void setAnnualPlanAl(String annualPlanAl) {
		this.annualPlanAl = annualPlanAl;
	}

	/**
	 * Gets the annual plan en.
	 *
	 * @return the annual plan en
	 */
	@Column(name = "annual_plan_en", nullable = false, length = 50)
	public String getAnnualPlanEn() {
		return this.annualPlanEn;
	}

	/**
	 * Sets the annual plan en.
	 *
	 * @param annualPlanEn the new annual plan en
	 */
	public void setAnnualPlanEn(String annualPlanEn) {
		this.annualPlanEn = annualPlanEn;
	}

	/**
	 * Gets the annual plan sr.
	 *
	 * @return the annual plan sr
	 */
	@Column(name = "annual_plan_sr", nullable = false, length = 50)
	public String getAnnualPlanSr() {
		return this.annualPlanSr;
	}

	/**
	 * Sets the annual plan sr.
	 *
	 * @param annualPlanSr the new annual plan sr
	 */
	public void setAnnualPlanSr(String annualPlanSr) {
		this.annualPlanSr = annualPlanSr;
	}

	/**
	 * Gets the submission date.
	 *
	 * @return the submission date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "submission_date", length = 13)
	public Date getSubmissionDate() {
		return this.submissionDate;
	}

	/**
	 * Sets the submission date.
	 *
	 * @param submissionDate the new submission date
	 */
	public void setSubmissionDate(Date submissionDate) {
		this.submissionDate = submissionDate;
	}

	/**
	 * Gets the comment.
	 *
	 * @return the comment
	 */
	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	/**
	 * Sets the comment.
	 *
	 * @param comment the new comment
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * Gets the hrm ann plan employees.
	 *
	 * @return the hrm ann plan employees
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hrmAnnualPlan")
	public Set<HrmAnnPlanEmployee> getHrmAnnPlanEmployees() {
		return this.hrmAnnPlanEmployees;
	}

	/**
	 * Sets the hrm ann plan employees.
	 *
	 * @param hrmAnnPlanEmployees the new hrm ann plan employees
	 */
	public void setHrmAnnPlanEmployees(
			Set<HrmAnnPlanEmployee> hrmAnnPlanEmployees) {
		this.hrmAnnPlanEmployees = hrmAnnPlanEmployees;
	}

	/**
	 * Gets the hrm annual plan docs.
	 *
	 * @return the hrm annual plan docs
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hrmAnnualPlan")
	public Set<HrmAnnualPlanDoc> getHrmAnnualPlanDocs() {
		return this.hrmAnnualPlanDocs;
	}

	/**
	 * Sets the hrm annual plan docs.
	 *
	 * @param hrmAnnualPlanDocs the new hrm annual plan docs
	 */
	public void setHrmAnnualPlanDocs(Set<HrmAnnualPlanDoc> hrmAnnualPlanDocs) {
		this.hrmAnnualPlanDocs = hrmAnnualPlanDocs;
	}

	/**
	 * Gets the hrm annual plan statuses.
	 *
	 * @return the hrm annual plan statuses
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hrmAnnualPlan")
	public Set<HrmAnnualPlanStatus> getHrmAnnualPlanStatuses() {
		return this.hrmAnnualPlanStatuses;
	}

	/**
	 * Sets the hrm annual plan statuses.
	 *
	 * @param hrmAnnualPlanStatuses the new hrm annual plan statuses
	 */
	public void setHrmAnnualPlanStatuses(
			Set<HrmAnnualPlanStatus> hrmAnnualPlanStatuses) {
		this.hrmAnnualPlanStatuses = hrmAnnualPlanStatuses;
	}

}
