package com.geoland.kfis.model;

// Generated Jun 11, 2015 9:39:14 AM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * HrmAnnPlanEmployee generated by hbm2java.
 */
@Entity
@Table(name = "thrm_ann_plan_employee", schema = "public")
public class HrmAnnPlanEmployee extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The hrm annual plan. */
	private HrmAnnualPlan hrmAnnualPlan;
	
	/** The employee. */
	private Employee employee;

	/**
	 * Instantiates a new hrm ann plan employee.
	 */
	public HrmAnnPlanEmployee() {
	}

	/**
	 * Instantiates a new hrm ann plan employee.
	 *
	 * @param hrmAnnualPlan the hrm annual plan
	 * @param employee the employee
	 */
	public HrmAnnPlanEmployee(HrmAnnualPlan hrmAnnualPlan, Employee employee) {
		this.hrmAnnualPlan = hrmAnnualPlan;
		this.employee = employee;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the hrm annual plan.
	 *
	 * @return the hrm annual plan
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ann_plan_id", nullable = false)
	public HrmAnnualPlan getHrmAnnualPlan() {
		return this.hrmAnnualPlan;
	}

	/**
	 * Sets the hrm annual plan.
	 *
	 * @param hrmAnnualPlan the new hrm annual plan
	 */
	public void setHrmAnnualPlan(HrmAnnualPlan hrmAnnualPlan) {
		this.hrmAnnualPlan = hrmAnnualPlan;
	}

	/**
	 * Gets the employee.
	 *
	 * @return the employee
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Sets the employee.
	 *
	 * @param employee the new employee
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

}
