package com.geoland.kfis.model;
// Generated Oct 24, 2017 10:02:34 AM by Hibernate Tools 4.0.1.Final

import com.geoland.framework.persistence.base.*;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.spatial.GeometryType;
import com.geoland.kfis.persistence.hibernate.usertypes.Linetempstatus;
import com.vividsolutions.jts.geom.Geometry;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * LineTemp generated by hbm2java.
 */
@Entity
@Table(name = "tlinetemp", schema = "public")
@TypeDef(name = "geometry", typeClass = GeometryType.class)
public class LineTemp extends AbstractPersistentObject implements java.io.Serializable {

	/** The id. */
	private Long id;
	
	/** The person by created by. */
	private Person personByCreatedBy;
	
	/** The person by changed by. */
	private Person personByChangedBy;
	
	/** The ltheme 12. */
	private String ltheme12;
	
	/** The quality cl. */
	private String qualityCl;
	
	/** The maintenanc. */
	private String maintenanc;
	
	/** The comment. */
	private String comment;
	
	/** The file format. */
	private String fileFormat;
	
	/** The date. */
	private Date date;
	
	/** The status. */
	private Linetempstatus status;
	
	/** The created date. */
	private Date createdDate;
	
	/** The changed date. */
	private Date changedDate;
	
	/** The geom. */
	private Geometry theGeom;

	/**
	 * Instantiates a new line temp.
	 */
	public LineTemp() {
	}

	/**
	 * Instantiates a new line temp.
	 *
	 * @param personByCreatedBy the person by created by
	 * @param createdDate the created date
	 */
	public LineTemp(Person personByCreatedBy, Date createdDate) {
		this.personByCreatedBy = personByCreatedBy;
		this.createdDate = createdDate;
	}

	/**
	 * Instantiates a new line temp.
	 *
	 * @param personByCreatedBy the person by created by
	 * @param personByChangedBy the person by changed by
	 * @param ltheme12 the ltheme 12
	 * @param qualityCl the quality cl
	 * @param maintenanc the maintenanc
	 * @param comment the comment
	 * @param fileFormat the file format
	 * @param date the date
	 * @param status the status
	 * @param createdDate the created date
	 * @param changedDate the changed date
	 * @param theGeom the the geom
	 */
	public LineTemp(Person personByCreatedBy, Person personByChangedBy, String ltheme12, String qualityCl,
			String maintenanc, String comment, String fileFormat, Date date, Linetempstatus status, Date createdDate,
			Date changedDate, Geometry theGeom) {
		this.personByCreatedBy = personByCreatedBy;
		this.personByChangedBy = personByChangedBy;
		this.ltheme12 = ltheme12;
		this.qualityCl = qualityCl;
		this.maintenanc = maintenanc;
		this.comment = comment;
		this.fileFormat = fileFormat;
		this.date = date;
		this.status = status;
		this.createdDate = createdDate;
		this.changedDate = changedDate;
		this.theGeom = theGeom;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the person by created by.
	 *
	 * @return the person by created by
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Person getPersonByCreatedBy() {
		return this.personByCreatedBy;
	}

	/**
	 * Sets the person by created by.
	 *
	 * @param personByCreatedBy the new person by created by
	 */
	public void setPersonByCreatedBy(Person personByCreatedBy) {
		this.personByCreatedBy = personByCreatedBy;
	}

	/**
	 * Gets the person by changed by.
	 *
	 * @return the person by changed by
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "changed_by")
	public Person getPersonByChangedBy() {
		return this.personByChangedBy;
	}

	/**
	 * Sets the person by changed by.
	 *
	 * @param personByChangedBy the new person by changed by
	 */
	public void setPersonByChangedBy(Person personByChangedBy) {
		this.personByChangedBy = personByChangedBy;
	}

	/**
	 * Gets the ltheme 12.
	 *
	 * @return the ltheme 12
	 */
	@Column(name = "ltheme12", length = 10)
	public String getLtheme12() {
		return this.ltheme12;
	}

	/**
	 * Sets the ltheme 12.
	 *
	 * @param ltheme12 the new ltheme 12
	 */
	public void setLtheme12(String ltheme12) {
		this.ltheme12 = ltheme12;
	}

	/**
	 * Gets the quality cl.
	 *
	 * @return the quality cl
	 */
	@Column(name = "quality_cl", length = 20)
	public String getQualityCl() {
		return this.qualityCl;
	}

	/**
	 * Sets the quality cl.
	 *
	 * @param qualityCl the new quality cl
	 */
	public void setQualityCl(String qualityCl) {
		this.qualityCl = qualityCl;
	}

	/**
	 * Gets the maintenanc.
	 *
	 * @return the maintenanc
	 */
	@Column(name = "maintenanc", length = 20)
	public String getMaintenanc() {
		return this.maintenanc;
	}

	/**
	 * Sets the maintenanc.
	 *
	 * @param maintenanc the new maintenanc
	 */
	public void setMaintenanc(String maintenanc) {
		this.maintenanc = maintenanc;
	}

	/**
	 * Gets the comment.
	 *
	 * @return the comment
	 */
	@Column(name = "comment")
	public String getComment() {
		return this.comment;
	}

	/**
	 * Sets the comment.
	 *
	 * @param comment the new comment
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * Gets the file format.
	 *
	 * @return the file format
	 */
	@Column(name = "file_format", length = 10)
	public String getFileFormat() {
		return this.fileFormat;
	}

	/**
	 * Sets the file format.
	 *
	 * @param fileFormat the new file format
	 */
	public void setFileFormat(String fileFormat) {
		this.fileFormat = fileFormat;
	}

	/**
	 * Gets the date.
	 *
	 * @return the date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 13)
	public Date getDate() {
		return this.date;
	}

	/**
	 * Sets the date.
	 *
	 * @param date the new date
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * Gets the status.
	 *
	 * @return the status
	 */
	@Column(name = "status", length = 2)

	@Type(type = "com.geoland.kfis.persistence.hibernate.usertypes.LinetempstatusUserType")
	public Linetempstatus getStatus() {
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(Linetempstatus status) {
		this.status = status;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * Gets the changed date.
	 *
	 * @return the changed date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "changed_date", length = 29)
	public Date getChangedDate() {
		return this.changedDate;
	}

	/**
	 * Sets the changed date.
	 *
	 * @param changedDate the new changed date
	 */
	public void setChangedDate(Date changedDate) {
		this.changedDate = changedDate;
	}

	/**
	 * Gets the the geom.
	 *
	 * @return the the geom
	 */
	@Column(name = "the_geom")
	@Type(type = "org.hibernate.spatial.GeometryType")
	public Geometry getTheGeom() {
		return this.theGeom;
	}

	/**
	 * Sets the the geom.
	 *
	 * @param theGeom the new the geom
	 */
	public void setTheGeom(Geometry theGeom) {
		this.theGeom = theGeom;
	}

}
