package com.geoland.kfis.model;

// Generated Feb 11, 2015 2:26:59 AM by Hibernate Tools 3.4.0.CR1

import com.geoland.framework.persistence.base.*;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * ManagmentProtocolDoc generated by hbm2java.
 */
@Entity
@Table(name = "tmanagment_protocol_doc", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "protocol_no"))
public class ManagmentProtocolDoc extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The party by created by. */
	private Party partyByCreatedBy;
	
	/** The party by department id. */
	private Party partyByDepartmentId;
	
	/** The protocol no. */
	private String protocolNo;
	
	/** The doc type. */
	private String docType;
	
	/** The doc name. */
	private String docName;
	
	/** The doc size. */
	private Long docSize;
	
	/** The doc. */
	private byte[] doc;
	
	/** The status. */
	private String status;
	
	/** The action taken. */
	private String actionTaken;
	
	/** The created date. */
	private Date createdDate;
	
	/** The note. */
	private String note;

	/**
	 * Instantiates a new managment protocol doc.
	 */
	public ManagmentProtocolDoc() {
	}

	/**
	 * Instantiates a new managment protocol doc.
	 *
	 * @param partyByCreatedBy the party by created by
	 * @param partyByDepartmentId the party by department id
	 * @param protocolNo the protocol no
	 * @param docType the doc type
	 * @param docName the doc name
	 * @param docSize the doc size
	 * @param doc the doc
	 * @param createdDate the created date
	 */
	public ManagmentProtocolDoc(Party partyByCreatedBy,
			Party partyByDepartmentId, String protocolNo, String docType,
			String docName, Long docSize, byte[] doc, Date createdDate) {
		this.partyByCreatedBy = partyByCreatedBy;
		this.partyByDepartmentId = partyByDepartmentId;
		this.protocolNo = protocolNo;
		this.docType = docType;
		this.docName = docName;
		this.docSize = docSize;
		this.doc = doc;
		this.createdDate = createdDate;
	}

	/**
	 * Instantiates a new managment protocol doc.
	 *
	 * @param partyByCreatedBy the party by created by
	 * @param partyByDepartmentId the party by department id
	 * @param protocolNo the protocol no
	 * @param docType the doc type
	 * @param docName the doc name
	 * @param docSize the doc size
	 * @param doc the doc
	 * @param status the status
	 * @param actionTaken the action taken
	 * @param createdDate the created date
	 * @param note the note
	 */
	public ManagmentProtocolDoc(Party partyByCreatedBy,
			Party partyByDepartmentId, String protocolNo, String docType,
			String docName, Long docSize, byte[] doc, String status,
			String actionTaken, Date createdDate, String note) {
		this.partyByCreatedBy = partyByCreatedBy;
		this.partyByDepartmentId = partyByDepartmentId;
		this.protocolNo = protocolNo;
		this.docType = docType;
		this.docName = docName;
		this.docSize = docSize;
		this.doc = doc;
		this.status = status;
		this.actionTaken = actionTaken;
		this.createdDate = createdDate;
		this.note = note;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the party by created by.
	 *
	 * @return the party by created by
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Party getPartyByCreatedBy() {
		return this.partyByCreatedBy;
	}

	/**
	 * Sets the party by created by.
	 *
	 * @param partyByCreatedBy the new party by created by
	 */
	public void setPartyByCreatedBy(Party partyByCreatedBy) {
		this.partyByCreatedBy = partyByCreatedBy;
	}

	/**
	 * Gets the party by department id.
	 *
	 * @return the party by department id
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "department_id", nullable = false)
	public Party getPartyByDepartmentId() {
		return this.partyByDepartmentId;
	}

	/**
	 * Sets the party by department id.
	 *
	 * @param partyByDepartmentId the new party by department id
	 */
	public void setPartyByDepartmentId(Party partyByDepartmentId) {
		this.partyByDepartmentId = partyByDepartmentId;
	}

	/**
	 * Gets the protocol no.
	 *
	 * @return the protocol no
	 */
	@Column(name = "protocol_no", unique = true, nullable = false, length = 50)
	public String getProtocolNo() {
		return this.protocolNo;
	}

	/**
	 * Sets the protocol no.
	 *
	 * @param protocolNo the new protocol no
	 */
	public void setProtocolNo(String protocolNo) {
		this.protocolNo = protocolNo;
	}

	/**
	 * Gets the doc type.
	 *
	 * @return the doc type
	 */
	@Column(name = "doc_type", nullable = false, length = 100)
	public String getDocType() {
		return this.docType;
	}

	/**
	 * Sets the doc type.
	 *
	 * @param docType the new doc type
	 */
	public void setDocType(String docType) {
		this.docType = docType;
	}

	/**
	 * Gets the doc name.
	 *
	 * @return the doc name
	 */
	@Column(name = "doc_name", nullable = false, length = 100)
	public String getDocName() {
		return this.docName;
	}

	/**
	 * Sets the doc name.
	 *
	 * @param docName the new doc name
	 */
	public void setDocName(String docName) {
		this.docName = docName;
	}

	/**
	 * Gets the doc size.
	 *
	 * @return the doc size
	 */
	@Column(name = "doc_size", nullable = false)
	public Long getDocSize() {
		return this.docSize;
	}

	/**
	 * Sets the doc size.
	 *
	 * @param docSize the new doc size
	 */
	public void setDocSize(Long docSize) {
		this.docSize = docSize;
	}

	/**
	 * Gets the doc.
	 *
	 * @return the doc
	 */
	@Column(name = "doc", nullable = false)
	public byte[] getDoc() {
		return this.doc;
	}

	/**
	 * Sets the doc.
	 *
	 * @param doc the new doc
	 */
	public void setDoc(byte[] doc) {
		this.doc = doc;
	}

	/**
	 * Gets the status.
	 *
	 * @return the status
	 */
	@Column(name = "status", length = 50)
	public String getStatus() {
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Gets the action taken.
	 *
	 * @return the action taken
	 */
	@Column(name = "action_taken", length = 50)
	public String getActionTaken() {
		return this.actionTaken;
	}

	/**
	 * Sets the action taken.
	 *
	 * @param actionTaken the new action taken
	 */
	public void setActionTaken(String actionTaken) {
		this.actionTaken = actionTaken;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * Gets the note.
	 *
	 * @return the note
	 */
	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	/**
	 * Sets the note.
	 *
	 * @param note the new note
	 */
	public void setNote(String note) {
		this.note = note;
	}

}
