package com.geoland.kfis.model;

// Generated Mar 25, 2015 2:09:17 PM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * MerRespInstitution generated by hbm2java.
 */
@Entity
@Table(name = "tmer_resp_institutions", schema = "public")
public class MerRespInstitution extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The person. */
	private Person person;
	
	/** The organisation. */
	private Organisation organisation;
	
	/** The mer strategy. */
	private MerStrategy merStrategy;
	
	/** The note. */
	private String note;
	
	/** The created date. */
	private Date createdDate;

	/**
	 * Instantiates a new mer resp institution.
	 */
	public MerRespInstitution() {
	}

	/**
	 * Instantiates a new mer resp institution.
	 *
	 * @param person the person
	 * @param organisation the organisation
	 * @param merStrategy the mer strategy
	 * @param createdDate the created date
	 */
	public MerRespInstitution(Person person, Organisation organisation,
			MerStrategy merStrategy, Date createdDate) {
		this.person = person;
		this.organisation = organisation;
		this.merStrategy = merStrategy;
		this.createdDate = createdDate;
	}

	/**
	 * Instantiates a new mer resp institution.
	 *
	 * @param person the person
	 * @param organisation the organisation
	 * @param merStrategy the mer strategy
	 * @param note the note
	 * @param createdDate the created date
	 */
	public MerRespInstitution(Person person, Organisation organisation,
			MerStrategy merStrategy, String note, Date createdDate) {
		this.person = person;
		this.organisation = organisation;
		this.merStrategy = merStrategy;
		this.note = note;
		this.createdDate = createdDate;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the person.
	 *
	 * @return the person
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	/**
	 * Sets the person.
	 *
	 * @param person the new person
	 */
	public void setPerson(Person person) {
		this.person = person;
	}

	/**
	 * Gets the organisation.
	 *
	 * @return the organisation
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organisation_id", nullable = false)
	public Organisation getOrganisation() {
		return this.organisation;
	}

	/**
	 * Sets the organisation.
	 *
	 * @param organisation the new organisation
	 */
	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	/**
	 * Gets the mer strategy.
	 *
	 * @return the mer strategy
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "strategy_id", nullable = false)
	public MerStrategy getMerStrategy() {
		return this.merStrategy;
	}

	/**
	 * Sets the mer strategy.
	 *
	 * @param merStrategy the new mer strategy
	 */
	public void setMerStrategy(MerStrategy merStrategy) {
		this.merStrategy = merStrategy;
	}

	/**
	 * Gets the note.
	 *
	 * @return the note
	 */
	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	/**
	 * Sets the note.
	 *
	 * @param note the new note
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", nullable = false, length = 13)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
