package com.geoland.kfis.model;

// Generated Feb 11, 2015 2:26:59 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import com.geoland.framework.persistence.base.AbstractPersistentObject;

// TODO: Auto-generated Javadoc
/**
 * PrcmtDossierQuestion generated by hbm2java.
 */
@Entity
@Table(name = "tprcmt_dossier_question", schema = "public")
public class PrcmtDossierQuestion extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The prcmt dossier request. */
	private PrcmtDossierRequest prcmtDossierRequest;
	
	/** The employee. */
	private Employee employee;
	
	/** The question. */
	private String question;
	
	/** The created date. */
	private Date createdDate;

	/**
	 * Instantiates a new prcmt dossier question.
	 */
	public PrcmtDossierQuestion() {
	}

	/**
	 * Instantiates a new prcmt dossier question.
	 *
	 * @param prcmtDossierRequest the prcmt dossier request
	 * @param employee the employee
	 * @param question the question
	 * @param createdDate the created date
	 */
	public PrcmtDossierQuestion(PrcmtDossierRequest prcmtDossierRequest,
			Employee employee, String question, Date createdDate) {
		this.prcmtDossierRequest = prcmtDossierRequest;
		this.employee = employee;
		this.question = question;
		this.createdDate = createdDate;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the prcmt dossier request.
	 *
	 * @return the prcmt dossier request
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dossier_request_id", nullable = false)
	public PrcmtDossierRequest getPrcmtDossierRequest() {
		return this.prcmtDossierRequest;
	}

	/**
	 * Sets the prcmt dossier request.
	 *
	 * @param prcmtDossierRequest the new prcmt dossier request
	 */
	public void setPrcmtDossierRequest(PrcmtDossierRequest prcmtDossierRequest) {
		this.prcmtDossierRequest = prcmtDossierRequest;
	}

	/**
	 * Gets the employee.
	 *
	 * @return the employee
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Sets the employee.
	 *
	 * @param employee the new employee
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	/**
	 * Gets the question.
	 *
	 * @return the question
	 */
	@Column(name = "question", nullable = false)
	public String getQuestion() {
		return this.question;
	}

	/**
	 * Sets the question.
	 *
	 * @param question the new question
	 */
	public void setQuestion(String question) {
		this.question = question;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
