package com.geoland.kfis.model;

// Generated May 21, 2015 4:15:19 PM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * Publishing generated by hbm2java.
 */
@Entity
@Table(name = "tpublishing", schema = "public")
public class Publishing extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The person. */
	private Person person;
	
	/** The html code. */
	private String htmlCode;
	
	/** The html code en. */
	private String htmlCodeEn;
	
	/** The html code sr. */
	private String htmlCodeSr;
	
	/** The title. */
	private String title;
	
	/** The title en. */
	private String titleEn;
	
	/** The title sr. */
	private String titleSr;
	
	/** The important. */
	private Boolean important;
	
	/** The published date. */
	private Date publishedDate;
	
	/** The published. */
	private boolean published;
	
	/** The photo. */
	private byte[] photo;
	
	/** The created date. */
	private Date createdDate;

	/**
	 * Instantiates a new publishing.
	 */
	public Publishing() {
	}

	/**
	 * Instantiates a new publishing.
	 *
	 * @param person the person
	 * @param htmlCode the html code
	 * @param title the title
	 * @param publishedDate the published date
	 * @param published the published
	 * @param createdDate the created date
	 */
	public Publishing(Person person, String htmlCode, String title,
			Date publishedDate, boolean published, Date createdDate) {
		this.person = person;
		this.htmlCode = htmlCode;
		this.title = title;
		this.publishedDate = publishedDate;
		this.published = published;
		this.createdDate = createdDate;
	}

	/**
	 * Instantiates a new publishing.
	 *
	 * @param person the person
	 * @param htmlCode the html code
	 * @param htmlCodeEn the html code en
	 * @param htmlCodeSr the html code sr
	 * @param title the title
	 * @param titleEn the title en
	 * @param titleSr the title sr
	 * @param important the important
	 * @param publishedDate the published date
	 * @param published the published
	 * @param photo the photo
	 * @param createdDate the created date
	 */
	public Publishing(Person person, String htmlCode, String htmlCodeEn,
			String htmlCodeSr, String title, String titleEn, String titleSr,
			Boolean important, Date publishedDate, boolean published,
			byte[] photo, Date createdDate) {
		this.person = person;
		this.htmlCode = htmlCode;
		this.htmlCodeEn = htmlCodeEn;
		this.htmlCodeSr = htmlCodeSr;
		this.title = title;
		this.titleEn = titleEn;
		this.titleSr = titleSr;
		this.important = important;
		this.publishedDate = publishedDate;
		this.published = published;
		this.photo = photo;
		this.createdDate = createdDate;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the person.
	 *
	 * @return the person
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	/**
	 * Sets the person.
	 *
	 * @param person the new person
	 */
	public void setPerson(Person person) {
		this.person = person;
	}

	/**
	 * Gets the html code.
	 *
	 * @return the html code
	 */
	@Column(name = "html_code", nullable = false)
	public String getHtmlCode() {
		return this.htmlCode;
	}

	/**
	 * Sets the html code.
	 *
	 * @param htmlCode the new html code
	 */
	public void setHtmlCode(String htmlCode) {
		this.htmlCode = htmlCode;
	}

	/**
	 * Gets the html code en.
	 *
	 * @return the html code en
	 */
	@Column(name = "html_code_en")
	public String getHtmlCodeEn() {
		return this.htmlCodeEn;
	}

	/**
	 * Sets the html code en.
	 *
	 * @param htmlCodeEn the new html code en
	 */
	public void setHtmlCodeEn(String htmlCodeEn) {
		this.htmlCodeEn = htmlCodeEn;
	}

	/**
	 * Gets the html code sr.
	 *
	 * @return the html code sr
	 */
	@Column(name = "html_code_sr")
	public String getHtmlCodeSr() {
		return this.htmlCodeSr;
	}

	/**
	 * Sets the html code sr.
	 *
	 * @param htmlCodeSr the new html code sr
	 */
	public void setHtmlCodeSr(String htmlCodeSr) {
		this.htmlCodeSr = htmlCodeSr;
	}

	/**
	 * Gets the title.
	 *
	 * @return the title
	 */
	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	/**
	 * Sets the title.
	 *
	 * @param title the new title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Gets the title en.
	 *
	 * @return the title en
	 */
	@Column(name = "title_en", length = 100)
	public String getTitleEn() {
		return this.titleEn;
	}

	/**
	 * Sets the title en.
	 *
	 * @param titleEn the new title en
	 */
	public void setTitleEn(String titleEn) {
		this.titleEn = titleEn;
	}

	/**
	 * Gets the title sr.
	 *
	 * @return the title sr
	 */
	@Column(name = "title_sr", length = 100)
	public String getTitleSr() {
		return this.titleSr;
	}

	/**
	 * Sets the title sr.
	 *
	 * @param titleSr the new title sr
	 */
	public void setTitleSr(String titleSr) {
		this.titleSr = titleSr;
	}

	/**
	 * Gets the important.
	 *
	 * @return the important
	 */
	@Column(name = "important")
	public Boolean getImportant() {
		return this.important;
	}

	/**
	 * Sets the important.
	 *
	 * @param important the new important
	 */
	public void setImportant(Boolean important) {
		this.important = important;
	}

	/**
	 * Gets the published date.
	 *
	 * @return the published date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "published_date", nullable = false, length = 13)
	public Date getPublishedDate() {
		return this.publishedDate;
	}

	/**
	 * Sets the published date.
	 *
	 * @param publishedDate the new published date
	 */
	public void setPublishedDate(Date publishedDate) {
		this.publishedDate = publishedDate;
	}

	/**
	 * Checks if is published.
	 *
	 * @return true, if is published
	 */
	@Column(name = "published", nullable = false)
	public boolean isPublished() {
		return this.published;
	}

	/**
	 * Sets the published.
	 *
	 * @param published the new published
	 */
	public void setPublished(boolean published) {
		this.published = published;
	}

	/**
	 * Gets the photo.
	 *
	 * @return the photo
	 */
	@Column(name = "photo")
	public byte[] getPhoto() {
		return this.photo;
	}

	/**
	 * Sets the photo.
	 *
	 * @param photo the new photo
	 */
	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", nullable = false, length = 13)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
