package com.geoland.kfis.model;

// Generated Mar 7, 2015 12:39:09 AM by Hibernate Tools 3.4.0.CR1

import com.geoland.framework.persistence.base.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * RequisitionStatus generated by hbm2java.
 */
@Entity
@Table(name = "trequisition_status", schema = "public")
public class RequisitionStatus extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The requisition. */
	private Requisition requisition;
	
	/** The person by createdby. */
	private Person personByCreatedby;
	
	/** The person by updatedby. */
	private Person personByUpdatedby;
	
	/** The status code. */
	private String statusCode;
	
	/** The textmsg. */
	private String textmsg;
	
	/** The created. */
	private Date created;
	
	/** The updated. */
	private Date updated;
	
	/** The requisitions. */
	private Set<Requisition> requisitions = new HashSet<Requisition>(0);

	/**
	 * Instantiates a new requisition status.
	 */
	public RequisitionStatus() {
	}

	/**
	 * Instantiates a new requisition status.
	 *
	 * @param requisition the requisition
	 * @param personByCreatedby the person by createdby
	 * @param personByUpdatedby the person by updatedby
	 * @param statusCode the status code
	 * @param created the created
	 * @param updated the updated
	 */
	public RequisitionStatus(Requisition requisition, Person personByCreatedby,
			Person personByUpdatedby, String statusCode, Date created,
			Date updated) {
		this.requisition = requisition;
		this.personByCreatedby = personByCreatedby;
		this.personByUpdatedby = personByUpdatedby;
		this.statusCode = statusCode;
		this.created = created;
		this.updated = updated;
	}

	/**
	 * Instantiates a new requisition status.
	 *
	 * @param requisition the requisition
	 * @param personByCreatedby the person by createdby
	 * @param personByUpdatedby the person by updatedby
	 * @param statusCode the status code
	 * @param textmsg the textmsg
	 * @param created the created
	 * @param updated the updated
	 * @param requisitions the requisitions
	 */
	public RequisitionStatus(Requisition requisition, Person personByCreatedby,
			Person personByUpdatedby, String statusCode, String textmsg,
			Date created, Date updated, Set<Requisition> requisitions) {
		this.requisition = requisition;
		this.personByCreatedby = personByCreatedby;
		this.personByUpdatedby = personByUpdatedby;
		this.statusCode = statusCode;
		this.textmsg = textmsg;
		this.created = created;
		this.updated = updated;
		this.requisitions = requisitions;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the requisition.
	 *
	 * @return the requisition
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "requisition_id", nullable = false)
	public Requisition getRequisition() {
		return this.requisition;
	}

	/**
	 * Sets the requisition.
	 *
	 * @param requisition the new requisition
	 */
	public void setRequisition(Requisition requisition) {
		this.requisition = requisition;
	}

	/**
	 * Gets the person by createdby.
	 *
	 * @return the person by createdby
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "createdby", nullable = false)
	public Person getPersonByCreatedby() {
		return this.personByCreatedby;
	}

	/**
	 * Sets the person by createdby.
	 *
	 * @param personByCreatedby the new person by createdby
	 */
	public void setPersonByCreatedby(Person personByCreatedby) {
		this.personByCreatedby = personByCreatedby;
	}

	/**
	 * Gets the person by updatedby.
	 *
	 * @return the person by updatedby
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedby", nullable = false)
	public Person getPersonByUpdatedby() {
		return this.personByUpdatedby;
	}

	/**
	 * Sets the person by updatedby.
	 *
	 * @param personByUpdatedby the new person by updatedby
	 */
	public void setPersonByUpdatedby(Person personByUpdatedby) {
		this.personByUpdatedby = personByUpdatedby;
	}

	/**
	 * Gets the status code.
	 *
	 * @return the status code
	 */
	@Column(name = "status_code", nullable = false, length = 20)
	public String getStatusCode() {
		return this.statusCode;
	}

	/**
	 * Sets the status code.
	 *
	 * @param statusCode the new status code
	 */
	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	/**
	 * Gets the textmsg.
	 *
	 * @return the textmsg
	 */
	@Column(name = "textmsg", length = 1000)
	public String getTextmsg() {
		return this.textmsg;
	}

	/**
	 * Sets the textmsg.
	 *
	 * @param textmsg the new textmsg
	 */
	public void setTextmsg(String textmsg) {
		this.textmsg = textmsg;
	}

	/**
	 * Gets the created.
	 *
	 * @return the created
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	/**
	 * Sets the created.
	 *
	 * @param created the new created
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * Gets the updated.
	 *
	 * @return the updated
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	/**
	 * Sets the updated.
	 *
	 * @param updated the new updated
	 */
	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	/**
	 * Gets the requisitions.
	 *
	 * @return the requisitions
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requisitionStatus")
	public Set<Requisition> getRequisitions() {
		return this.requisitions;
	}

	/**
	 * Sets the requisitions.
	 *
	 * @param requisitions the new requisitions
	 */
	public void setRequisitions(Set<Requisition> requisitions) {
		this.requisitions = requisitions;
	}

}
