package com.geoland.kfis.model;

// Generated Mar 7, 2015 12:39:09 AM by Hibernate Tools 3.4.0.CR1

import com.geoland.framework.persistence.base.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * Requisition generated by hbm2java.
 */
@Entity
@Table(name = "trequisition", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "requisition_nr"))
public class Requisition extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The currency. */
	private Currency currency;
	
	/** The bpartner. */
	private Bpartner bpartner;
	
	/** The person by updatedby. */
	private Person personByUpdatedby;
	
	/** The person by createdby. */
	private Person personByCreatedby;
	
	/** The requisition status. */
	private RequisitionStatus requisitionStatus;
	
	/** The organisation. */
	private Organisation organisation;
	
	/** The dp mngmt. */
	private DpMngmt dpMngmt;
	
	/** The isactive. */
	private String isactive;
	
	/** The requisition nr. */
	private String requisitionNr;
	
	/** The status code. */
	private String statusCode;
	
	/** The requester name. */
	private String requesterName;
	
	/** The requester phone. */
	private String requesterPhone;
	
	/** The destination type. */
	private String destinationType;
	
	/** The is bpartner. */
	private String isBpartner;
	
	/** The supplier name. */
	private String supplierName;
	
	/** The supplier site. */
	private String supplierSite;
	
	/** The supplier contact. */
	private String supplierContact;
	
	/** The supplier phone. */
	private String supplierPhone;
	
	/** The supplier address. */
	private String supplierAddress;
	
	/** The supplier fax. */
	private String supplierFax;
	
	/** The supplier email. */
	private String supplierEmail;
	
	/** The total amount. */
	private BigDecimal totalAmount;
	
	/** The desired date. */
	private Date desiredDate;
	
	/** The created. */
	private Date created;
	
	/** The updated. */
	private Date updated;
	
	/** The textmsg. */
	private String textmsg;
	
	/** The is po. */
	private String isPo;
	
	/** The requisition statuses. */
	private Set<RequisitionStatus> requisitionStatuses = new HashSet<RequisitionStatus>(
			0);
	
	/** The requisition items. */
	private Set<RequisitionItem> requisitionItems = new HashSet<RequisitionItem>(
			0);
	
	/** The purchase orders. */
	private Set<PurchaseOrder> purchaseOrders = new HashSet<PurchaseOrder>(0);

	/**
	 * Instantiates a new requisition.
	 */
	public Requisition() {
	}

	/**
	 * Instantiates a new requisition.
	 *
	 * @param currency the currency
	 * @param personByUpdatedby the person by updatedby
	 * @param personByCreatedby the person by createdby
	 * @param organisation the organisation
	 * @param isactive the isactive
	 * @param requisitionNr the requisition nr
	 * @param requesterName the requester name
	 * @param requesterPhone the requester phone
	 * @param destinationType the destination type
	 * @param isBpartner the is bpartner
	 * @param created the created
	 * @param updated the updated
	 * @param isPo the is po
	 */
	public Requisition(Currency currency, Person personByUpdatedby,
			Person personByCreatedby, Organisation organisation,
			String isactive, String requisitionNr, String requesterName,
			String requesterPhone, String destinationType, String isBpartner,
			Date created, Date updated, String isPo) {
		this.currency = currency;
		this.personByUpdatedby = personByUpdatedby;
		this.personByCreatedby = personByCreatedby;
		this.organisation = organisation;
		this.isactive = isactive;
		this.requisitionNr = requisitionNr;
		this.requesterName = requesterName;
		this.requesterPhone = requesterPhone;
		this.destinationType = destinationType;
		this.isBpartner = isBpartner;
		this.created = created;
		this.updated = updated;
		this.isPo = isPo;
	}

	/**
	 * Instantiates a new requisition.
	 *
	 * @param currency the currency
	 * @param bpartner the bpartner
	 * @param personByUpdatedby the person by updatedby
	 * @param personByCreatedby the person by createdby
	 * @param requisitionStatus the requisition status
	 * @param organisation the organisation
	 * @param dpMngmt the dp mngmt
	 * @param isactive the isactive
	 * @param requisitionNr the requisition nr
	 * @param statusCode the status code
	 * @param requesterName the requester name
	 * @param requesterPhone the requester phone
	 * @param destinationType the destination type
	 * @param isBpartner the is bpartner
	 * @param supplierName the supplier name
	 * @param supplierSite the supplier site
	 * @param supplierContact the supplier contact
	 * @param supplierPhone the supplier phone
	 * @param supplierAddress the supplier address
	 * @param supplierFax the supplier fax
	 * @param supplierEmail the supplier email
	 * @param totalAmount the total amount
	 * @param desiredDate the desired date
	 * @param created the created
	 * @param updated the updated
	 * @param textmsg the textmsg
	 * @param isPo the is po
	 * @param requisitionStatuses the requisition statuses
	 * @param requisitionItems the requisition items
	 * @param purchaseOrders the purchase orders
	 */
	public Requisition(Currency currency, Bpartner bpartner,
			Person personByUpdatedby, Person personByCreatedby,
			RequisitionStatus requisitionStatus, Organisation organisation,
			DpMngmt dpMngmt, String isactive, String requisitionNr,
			String statusCode, String requesterName, String requesterPhone,
			String destinationType, String isBpartner, String supplierName,
			String supplierSite, String supplierContact, String supplierPhone,
			String supplierAddress, String supplierFax, String supplierEmail,
			BigDecimal totalAmount, Date desiredDate, Date created,
			Date updated, String textmsg, String isPo,
			Set<RequisitionStatus> requisitionStatuses,
			Set<RequisitionItem> requisitionItems,
			Set<PurchaseOrder> purchaseOrders) {
		this.currency = currency;
		this.bpartner = bpartner;
		this.personByUpdatedby = personByUpdatedby;
		this.personByCreatedby = personByCreatedby;
		this.requisitionStatus = requisitionStatus;
		this.organisation = organisation;
		this.dpMngmt = dpMngmt;
		this.isactive = isactive;
		this.requisitionNr = requisitionNr;
		this.statusCode = statusCode;
		this.requesterName = requesterName;
		this.requesterPhone = requesterPhone;
		this.destinationType = destinationType;
		this.isBpartner = isBpartner;
		this.supplierName = supplierName;
		this.supplierSite = supplierSite;
		this.supplierContact = supplierContact;
		this.supplierPhone = supplierPhone;
		this.supplierAddress = supplierAddress;
		this.supplierFax = supplierFax;
		this.supplierEmail = supplierEmail;
		this.totalAmount = totalAmount;
		this.desiredDate = desiredDate;
		this.created = created;
		this.updated = updated;
		this.textmsg = textmsg;
		this.isPo = isPo;
		this.requisitionStatuses = requisitionStatuses;
		this.requisitionItems = requisitionItems;
		this.purchaseOrders = purchaseOrders;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the currency.
	 *
	 * @return the currency
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "currency_id", nullable = false)
	public Currency getCurrency() {
		return this.currency;
	}

	/**
	 * Sets the currency.
	 *
	 * @param currency the new currency
	 */
	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	/**
	 * Gets the bpartner.
	 *
	 * @return the bpartner
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bpartner_id")
	public Bpartner getBpartner() {
		return this.bpartner;
	}

	/**
	 * Sets the bpartner.
	 *
	 * @param bpartner the new bpartner
	 */
	public void setBpartner(Bpartner bpartner) {
		this.bpartner = bpartner;
	}

	/**
	 * Gets the person by updatedby.
	 *
	 * @return the person by updatedby
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedby", nullable = false)
	public Person getPersonByUpdatedby() {
		return this.personByUpdatedby;
	}

	/**
	 * Sets the person by updatedby.
	 *
	 * @param personByUpdatedby the new person by updatedby
	 */
	public void setPersonByUpdatedby(Person personByUpdatedby) {
		this.personByUpdatedby = personByUpdatedby;
	}

	/**
	 * Gets the person by createdby.
	 *
	 * @return the person by createdby
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "createdby", nullable = false)
	public Person getPersonByCreatedby() {
		return this.personByCreatedby;
	}

	/**
	 * Sets the person by createdby.
	 *
	 * @param personByCreatedby the new person by createdby
	 */
	public void setPersonByCreatedby(Person personByCreatedby) {
		this.personByCreatedby = personByCreatedby;
	}

	/**
	 * Gets the requisition status.
	 *
	 * @return the requisition status
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id")
	public RequisitionStatus getRequisitionStatus() {
		return this.requisitionStatus;
	}

	/**
	 * Sets the requisition status.
	 *
	 * @param requisitionStatus the new requisition status
	 */
	public void setRequisitionStatus(RequisitionStatus requisitionStatus) {
		this.requisitionStatus = requisitionStatus;
	}

	/**
	 * Gets the organisation.
	 *
	 * @return the organisation
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organisation_id", nullable = false)
	public Organisation getOrganisation() {
		return this.organisation;
	}

	/**
	 * Sets the organisation.
	 *
	 * @param organisation the new organisation
	 */
	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	/**
	 * Gets the dp mngmt.
	 *
	 * @return the dp mngmt
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "document_id")
	public DpMngmt getDpMngmt() {
		return this.dpMngmt;
	}

	/**
	 * Sets the dp mngmt.
	 *
	 * @param dpMngmt the new dp mngmt
	 */
	public void setDpMngmt(DpMngmt dpMngmt) {
		this.dpMngmt = dpMngmt;
	}

	/**
	 * Gets the isactive.
	 *
	 * @return the isactive
	 */
	@Column(name = "isactive", nullable = false, length = 1)
	public String getIsactive() {
		return this.isactive;
	}

	/**
	 * Sets the isactive.
	 *
	 * @param isactive the new isactive
	 */
	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

	/**
	 * Gets the requisition nr.
	 *
	 * @return the requisition nr
	 */
	@Column(name = "requisition_nr", unique = true, nullable = false, length = 36)
	public String getRequisitionNr() {
		return this.requisitionNr;
	}

	/**
	 * Sets the requisition nr.
	 *
	 * @param requisitionNr the new requisition nr
	 */
	public void setRequisitionNr(String requisitionNr) {
		this.requisitionNr = requisitionNr;
	}

	/**
	 * Gets the status code.
	 *
	 * @return the status code
	 */
	@Column(name = "status_code", length = 20)
	public String getStatusCode() {
		return this.statusCode;
	}

	/**
	 * Sets the status code.
	 *
	 * @param statusCode the new status code
	 */
	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}

	/**
	 * Gets the requester name.
	 *
	 * @return the requester name
	 */
	@Column(name = "requester_name", nullable = false, length = 100)
	public String getRequesterName() {
		return this.requesterName;
	}

	/**
	 * Sets the requester name.
	 *
	 * @param requesterName the new requester name
	 */
	public void setRequesterName(String requesterName) {
		this.requesterName = requesterName;
	}

	/**
	 * Gets the requester phone.
	 *
	 * @return the requester phone
	 */
	@Column(name = "requester_phone", nullable = false, length = 100)
	public String getRequesterPhone() {
		return this.requesterPhone;
	}

	/**
	 * Sets the requester phone.
	 *
	 * @param requesterPhone the new requester phone
	 */
	public void setRequesterPhone(String requesterPhone) {
		this.requesterPhone = requesterPhone;
	}

	/**
	 * Gets the destination type.
	 *
	 * @return the destination type
	 */
	@Column(name = "destination_type", nullable = false, length = 1)
	public String getDestinationType() {
		return this.destinationType;
	}

	/**
	 * Sets the destination type.
	 *
	 * @param destinationType the new destination type
	 */
	public void setDestinationType(String destinationType) {
		this.destinationType = destinationType;
	}

	/**
	 * Gets the checks if is bpartner.
	 *
	 * @return the checks if is bpartner
	 */
	@Column(name = "is_bpartner", nullable = false, length = 1)
	public String getIsBpartner() {
		return this.isBpartner;
	}

	/**
	 * Sets the checks if is bpartner.
	 *
	 * @param isBpartner the new checks if is bpartner
	 */
	public void setIsBpartner(String isBpartner) {
		this.isBpartner = isBpartner;
	}

	/**
	 * Gets the supplier name.
	 *
	 * @return the supplier name
	 */
	@Column(name = "supplier_name", length = 100)
	public String getSupplierName() {
		return this.supplierName;
	}

	/**
	 * Sets the supplier name.
	 *
	 * @param supplierName the new supplier name
	 */
	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	/**
	 * Gets the supplier site.
	 *
	 * @return the supplier site
	 */
	@Column(name = "supplier_site", length = 100)
	public String getSupplierSite() {
		return this.supplierSite;
	}

	/**
	 * Sets the supplier site.
	 *
	 * @param supplierSite the new supplier site
	 */
	public void setSupplierSite(String supplierSite) {
		this.supplierSite = supplierSite;
	}

	/**
	 * Gets the supplier contact.
	 *
	 * @return the supplier contact
	 */
	@Column(name = "supplier_contact", length = 100)
	public String getSupplierContact() {
		return this.supplierContact;
	}

	/**
	 * Sets the supplier contact.
	 *
	 * @param supplierContact the new supplier contact
	 */
	public void setSupplierContact(String supplierContact) {
		this.supplierContact = supplierContact;
	}

	/**
	 * Gets the supplier phone.
	 *
	 * @return the supplier phone
	 */
	@Column(name = "supplier_phone", length = 100)
	public String getSupplierPhone() {
		return this.supplierPhone;
	}

	/**
	 * Sets the supplier phone.
	 *
	 * @param supplierPhone the new supplier phone
	 */
	public void setSupplierPhone(String supplierPhone) {
		this.supplierPhone = supplierPhone;
	}

	/**
	 * Gets the supplier address.
	 *
	 * @return the supplier address
	 */
	@Column(name = "supplier_address", length = 150)
	public String getSupplierAddress() {
		return this.supplierAddress;
	}

	/**
	 * Sets the supplier address.
	 *
	 * @param supplierAddress the new supplier address
	 */
	public void setSupplierAddress(String supplierAddress) {
		this.supplierAddress = supplierAddress;
	}

	/**
	 * Gets the supplier fax.
	 *
	 * @return the supplier fax
	 */
	@Column(name = "supplier_fax", length = 50)
	public String getSupplierFax() {
		return this.supplierFax;
	}

	/**
	 * Sets the supplier fax.
	 *
	 * @param supplierFax the new supplier fax
	 */
	public void setSupplierFax(String supplierFax) {
		this.supplierFax = supplierFax;
	}

	/**
	 * Gets the supplier email.
	 *
	 * @return the supplier email
	 */
	@Column(name = "supplier_email", length = 150)
	public String getSupplierEmail() {
		return this.supplierEmail;
	}

	/**
	 * Sets the supplier email.
	 *
	 * @param supplierEmail the new supplier email
	 */
	public void setSupplierEmail(String supplierEmail) {
		this.supplierEmail = supplierEmail;
	}

	/**
	 * Gets the total amount.
	 *
	 * @return the total amount
	 */
	@Column(name = "total_amount", precision = 20, scale = 5)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	/**
	 * Sets the total amount.
	 *
	 * @param totalAmount the new total amount
	 */
	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	/**
	 * Gets the desired date.
	 *
	 * @return the desired date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "desired_date", length = 29)
	public Date getDesiredDate() {
		return this.desiredDate;
	}

	/**
	 * Sets the desired date.
	 *
	 * @param desiredDate the new desired date
	 */
	public void setDesiredDate(Date desiredDate) {
		this.desiredDate = desiredDate;
	}

	/**
	 * Gets the created.
	 *
	 * @return the created
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	/**
	 * Sets the created.
	 *
	 * @param created the new created
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * Gets the updated.
	 *
	 * @return the updated
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	/**
	 * Sets the updated.
	 *
	 * @param updated the new updated
	 */
	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	/**
	 * Gets the textmsg.
	 *
	 * @return the textmsg
	 */
	@Column(name = "textmsg", length = 2000)
	public String getTextmsg() {
		return this.textmsg;
	}

	/**
	 * Sets the textmsg.
	 *
	 * @param textmsg the new textmsg
	 */
	public void setTextmsg(String textmsg) {
		this.textmsg = textmsg;
	}

	/**
	 * Gets the checks if is po.
	 *
	 * @return the checks if is po
	 */
	@Column(name = "is_po", nullable = false, length = 1)
	public String getIsPo() {
		return this.isPo;
	}

	/**
	 * Sets the checks if is po.
	 *
	 * @param isPo the new checks if is po
	 */
	public void setIsPo(String isPo) {
		this.isPo = isPo;
	}

	/**
	 * Gets the requisition statuses.
	 *
	 * @return the requisition statuses
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requisition")
	public Set<RequisitionStatus> getRequisitionStatuses() {
		return this.requisitionStatuses;
	}

	/**
	 * Sets the requisition statuses.
	 *
	 * @param requisitionStatuses the new requisition statuses
	 */
	public void setRequisitionStatuses(
			Set<RequisitionStatus> requisitionStatuses) {
		this.requisitionStatuses = requisitionStatuses;
	}

	/**
	 * Gets the requisition items.
	 *
	 * @return the requisition items
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requisition")
	public Set<RequisitionItem> getRequisitionItems() {
		return this.requisitionItems;
	}

	/**
	 * Sets the requisition items.
	 *
	 * @param requisitionItems the new requisition items
	 */
	public void setRequisitionItems(Set<RequisitionItem> requisitionItems) {
		this.requisitionItems = requisitionItems;
	}

	/**
	 * Gets the purchase orders.
	 *
	 * @return the purchase orders
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requisition")
	public Set<PurchaseOrder> getPurchaseOrders() {
		return this.purchaseOrders;
	}

	/**
	 * Sets the purchase orders.
	 *
	 * @param purchaseOrders the new purchase orders
	 */
	public void setPurchaseOrders(Set<PurchaseOrder> purchaseOrders) {
		this.purchaseOrders = purchaseOrders;
	}

}
