package com.geoland.kfis.model;

// Generated Mar 12, 2015 9:24:29 AM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * RoadActivity generated by hbm2java.
 */
@Entity
@Table(name = "tfrm_road_activity", schema = "public")
public class RoadActivity extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The person by im created by. */
	private Person personByImCreatedBy;
	
	/** The road. */
	private Road road;
	
	/** The activity. */
	private Activity activity;
	
	/** The activity status. */
	private ActivityStatus activityStatus;
	
	/** The person by pl created by. */
	private Person personByPlCreatedBy;
	
	/** The work stage. */
	private String workStage;
	
	/** The pl lenght. */
	private Double plLenght;
	
	/** The pl start M. */
	private Double plStartM;
	
	/** The pl end M. */
	private Double plEndM;
	
	/** The pl width. */
	private Double plWidth;
	
	/** The pl created date. */
	private Date plCreatedDate;
	
	/** The im lenght. */
	private Double imLenght;
	
	/** The im start M. */
	private Double imStartM;
	
	/** The im end M. */
	private Double imEndM;
	
	/** The im width. */
	private Double imWidth;
	
	/** The im created date. */
	private Date imCreatedDate;

	/**
	 * Instantiates a new road activity.
	 */
	public RoadActivity() {
	}

	/**
	 * Instantiates a new road activity.
	 *
	 * @param road the road
	 * @param activity the activity
	 * @param activityStatus the activity status
	 * @param workStage the work stage
	 * @param plLenght the pl lenght
	 * @param plStartM the pl start M
	 * @param plEndM the pl end M
	 * @param plWidth the pl width
	 */
	public RoadActivity(Road road, Activity activity,
			ActivityStatus activityStatus, String workStage, Double plLenght,
			Double plStartM, Double plEndM, Double plWidth) {
		this.road = road;
		this.activity = activity;
		this.activityStatus = activityStatus;
		this.workStage = workStage;
		this.plLenght = plLenght;
		this.plStartM = plStartM;
		this.plEndM = plEndM;
		this.plWidth = plWidth;
	}

	/**
	 * Instantiates a new road activity.
	 *
	 * @param personByImCreatedBy the person by im created by
	 * @param road the road
	 * @param activity the activity
	 * @param activityStatus the activity status
	 * @param personByPlCreatedBy the person by pl created by
	 * @param workStage the work stage
	 * @param plLenght the pl lenght
	 * @param plStartM the pl start M
	 * @param plEndM the pl end M
	 * @param plWidth the pl width
	 * @param plCreatedDate the pl created date
	 * @param imLenght the im lenght
	 * @param imStartM the im start M
	 * @param imEndM the im end M
	 * @param imWidth the im width
	 * @param imCreatedDate the im created date
	 */
	public RoadActivity(Person personByImCreatedBy, Road road,
			Activity activity, ActivityStatus activityStatus,
			Person personByPlCreatedBy, String workStage, Double plLenght,
			Double plStartM, Double plEndM, Double plWidth, Date plCreatedDate,
			Double imLenght, Double imStartM, Double imEndM, Double imWidth,
			Date imCreatedDate) {
		this.personByImCreatedBy = personByImCreatedBy;
		this.road = road;
		this.activity = activity;
		this.activityStatus = activityStatus;
		this.personByPlCreatedBy = personByPlCreatedBy;
		this.workStage = workStage;
		this.plLenght = plLenght;
		this.plStartM = plStartM;
		this.plEndM = plEndM;
		this.plWidth = plWidth;
		this.plCreatedDate = plCreatedDate;
		this.imLenght = imLenght;
		this.imStartM = imStartM;
		this.imEndM = imEndM;
		this.imWidth = imWidth;
		this.imCreatedDate = imCreatedDate;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the person by im created by.
	 *
	 * @return the person by im created by
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "im_created_by")
	public Person getPersonByImCreatedBy() {
		return this.personByImCreatedBy;
	}

	/**
	 * Sets the person by im created by.
	 *
	 * @param personByImCreatedBy the new person by im created by
	 */
	public void setPersonByImCreatedBy(Person personByImCreatedBy) {
		this.personByImCreatedBy = personByImCreatedBy;
	}

	/**
	 * Gets the road.
	 *
	 * @return the road
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "road_id", nullable = false)
	public Road getRoad() {
		return this.road;
	}

	/**
	 * Sets the road.
	 *
	 * @param road the new road
	 */
	public void setRoad(Road road) {
		this.road = road;
	}

	/**
	 * Gets the activity.
	 *
	 * @return the activity
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "activity_id", nullable = false)
	public Activity getActivity() {
		return this.activity;
	}

	/**
	 * Sets the activity.
	 *
	 * @param activity the new activity
	 */
	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	/**
	 * Gets the activity status.
	 *
	 * @return the activity status
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id", nullable = false)
	public ActivityStatus getActivityStatus() {
		return this.activityStatus;
	}

	/**
	 * Sets the activity status.
	 *
	 * @param activityStatus the new activity status
	 */
	public void setActivityStatus(ActivityStatus activityStatus) {
		this.activityStatus = activityStatus;
	}

	/**
	 * Gets the person by pl created by.
	 *
	 * @return the person by pl created by
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pl_created_by")
	public Person getPersonByPlCreatedBy() {
		return this.personByPlCreatedBy;
	}

	/**
	 * Sets the person by pl created by.
	 *
	 * @param personByPlCreatedBy the new person by pl created by
	 */
	public void setPersonByPlCreatedBy(Person personByPlCreatedBy) {
		this.personByPlCreatedBy = personByPlCreatedBy;
	}

	/**
	 * Gets the work stage.
	 *
	 * @return the work stage
	 */
	@Column(name = "work_stage", nullable = false, length = 1)
	public String getWorkStage() {
		return this.workStage;
	}

	/**
	 * Sets the work stage.
	 *
	 * @param workStage the new work stage
	 */
	public void setWorkStage(String workStage) {
		this.workStage = workStage;
	}

	/**
	 * Gets the pl lenght.
	 *
	 * @return the pl lenght
	 */
	@Column(name = "pl_lenght", nullable = false, precision = 17, scale = 17)
	public Double getPlLenght() {
		return this.plLenght;
	}

	/**
	 * Sets the pl lenght.
	 *
	 * @param plLenght the new pl lenght
	 */
	public void setPlLenght(Double plLenght) {
		this.plLenght = plLenght;
	}

	/**
	 * Gets the pl start M.
	 *
	 * @return the pl start M
	 */
	@Column(name = "pl_start_m", nullable = false, precision = 17, scale = 17)
	public Double getPlStartM() {
		return this.plStartM;
	}

	/**
	 * Sets the pl start M.
	 *
	 * @param plStartM the new pl start M
	 */
	public void setPlStartM(Double plStartM) {
		this.plStartM = plStartM;
	}

	/**
	 * Gets the pl end M.
	 *
	 * @return the pl end M
	 */
	@Column(name = "pl_end_m", nullable = false, precision = 17, scale = 17)
	public Double getPlEndM() {
		return this.plEndM;
	}

	/**
	 * Sets the pl end M.
	 *
	 * @param plEndM the new pl end M
	 */
	public void setPlEndM(Double plEndM) {
		this.plEndM = plEndM;
	}

	/**
	 * Gets the pl width.
	 *
	 * @return the pl width
	 */
	@Column(name = "pl_width", nullable = false, precision = 17, scale = 17)
	public Double getPlWidth() {
		return this.plWidth;
	}

	/**
	 * Sets the pl width.
	 *
	 * @param plWidth the new pl width
	 */
	public void setPlWidth(Double plWidth) {
		this.plWidth = plWidth;
	}

	/**
	 * Gets the pl created date.
	 *
	 * @return the pl created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pl_created_date", length = 29)
	public Date getPlCreatedDate() {
		return this.plCreatedDate;
	}

	/**
	 * Sets the pl created date.
	 *
	 * @param plCreatedDate the new pl created date
	 */
	public void setPlCreatedDate(Date plCreatedDate) {
		this.plCreatedDate = plCreatedDate;
	}

	/**
	 * Gets the im lenght.
	 *
	 * @return the im lenght
	 */
	@Column(name = "im_lenght", precision = 17, scale = 17)
	public Double getImLenght() {
		return this.imLenght;
	}

	/**
	 * Sets the im lenght.
	 *
	 * @param imLenght the new im lenght
	 */
	public void setImLenght(Double imLenght) {
		this.imLenght = imLenght;
	}

	/**
	 * Gets the im start M.
	 *
	 * @return the im start M
	 */
	@Column(name = "im_start_m", precision = 17, scale = 17)
	public Double getImStartM() {
		return this.imStartM;
	}

	/**
	 * Sets the im start M.
	 *
	 * @param imStartM the new im start M
	 */
	public void setImStartM(Double imStartM) {
		this.imStartM = imStartM;
	}

	/**
	 * Gets the im end M.
	 *
	 * @return the im end M
	 */
	@Column(name = "im_end_m", precision = 17, scale = 17)
	public Double getImEndM() {
		return this.imEndM;
	}

	/**
	 * Sets the im end M.
	 *
	 * @param imEndM the new im end M
	 */
	public void setImEndM(Double imEndM) {
		this.imEndM = imEndM;
	}

	/**
	 * Gets the im width.
	 *
	 * @return the im width
	 */
	@Column(name = "im_width", precision = 17, scale = 17)
	public Double getImWidth() {
		return this.imWidth;
	}

	/**
	 * Sets the im width.
	 *
	 * @param imWidth the new im width
	 */
	public void setImWidth(Double imWidth) {
		this.imWidth = imWidth;
	}

	/**
	 * Gets the im created date.
	 *
	 * @return the im created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "im_created_date", length = 29)
	public Date getImCreatedDate() {
		return this.imCreatedDate;
	}

	/**
	 * Sets the im created date.
	 *
	 * @param imCreatedDate the new im created date
	 */
	public void setImCreatedDate(Date imCreatedDate) {
		this.imCreatedDate = imCreatedDate;
	}

}
