package com.geoland.kfis.model;

// Generated Feb 19, 2015 2:38:46 PM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import org.hibernate.annotations.Type;
import com.geoland.kfis.persistence.hibernate.usertypes.Prodtype;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * SeedlingInventory generated by hbm2java.
 */
@Entity
@Table(name = "tfrm_seedling_inventory", schema = "public")
public class SeedlingInventory extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The seed activity. */
	private SeedActivity seedActivity;
	
	/** The person by created by. */
	private Person personByCreatedBy;
	
	/** The tree species. */
	private TreeSpecies treeSpecies;
	
	/** The person by changed by. */
	private Person personByChangedBy;
	
	/** The prod type. */
	private Prodtype prodType;
	
	/** The age. */
	private Short age;
	
	/** The seed year. */
	private Long seedYear;
	
	/** The stock. */
	private Long stock;
	
	/** The price. */
	private BigDecimal price;
	
	/** The created date. */
	private Date createdDate;
	
	/** The changed date. */
	private Date changedDate;
	
	/** The seedling inventory PO ss. */
	private Set<SeedlingInventoryPOS> seedlingInventoryPOSs = new HashSet<SeedlingInventoryPOS>(
			0);

	/**
	 * Instantiates a new seedling inventory.
	 */
	public SeedlingInventory() {
	}

	/**
	 * Instantiates a new seedling inventory.
	 *
	 * @param personByCreatedBy the person by created by
	 * @param treeSpecies the tree species
	 * @param prodType the prod type
	 * @param age the age
	 * @param seedYear the seed year
	 * @param stock the stock
	 * @param createdDate the created date
	 */
	public SeedlingInventory(Person personByCreatedBy, TreeSpecies treeSpecies,
			Prodtype prodType, Short age, Long seedYear, Long stock,
			Date createdDate) {
		this.personByCreatedBy = personByCreatedBy;
		this.treeSpecies = treeSpecies;
		this.prodType = prodType;
		this.age = age;
		this.seedYear = seedYear;
		this.stock = stock;
		this.createdDate = createdDate;
	}

	/**
	 * Instantiates a new seedling inventory.
	 *
	 * @param seedActivity the seed activity
	 * @param personByCreatedBy the person by created by
	 * @param treeSpecies the tree species
	 * @param personByChangedBy the person by changed by
	 * @param prodType the prod type
	 * @param age the age
	 * @param seedYear the seed year
	 * @param stock the stock
	 * @param price the price
	 * @param createdDate the created date
	 * @param changedDate the changed date
	 * @param seedlingInventoryPOSs the seedling inventory PO ss
	 */
	public SeedlingInventory(SeedActivity seedActivity,
			Person personByCreatedBy, TreeSpecies treeSpecies,
			Person personByChangedBy, Prodtype prodType, Short age,
			Long seedYear, Long stock, BigDecimal price, Date createdDate,
			Date changedDate, Set<SeedlingInventoryPOS> seedlingInventoryPOSs) {
		this.seedActivity = seedActivity;
		this.personByCreatedBy = personByCreatedBy;
		this.treeSpecies = treeSpecies;
		this.personByChangedBy = personByChangedBy;
		this.prodType = prodType;
		this.age = age;
		this.seedYear = seedYear;
		this.stock = stock;
		this.price = price;
		this.createdDate = createdDate;
		this.changedDate = changedDate;
		this.seedlingInventoryPOSs = seedlingInventoryPOSs;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the seed activity.
	 *
	 * @return the seed activity
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seed_activity_id")
	public SeedActivity getSeedActivity() {
		return this.seedActivity;
	}

	/**
	 * Sets the seed activity.
	 *
	 * @param seedActivity the new seed activity
	 */
	public void setSeedActivity(SeedActivity seedActivity) {
		this.seedActivity = seedActivity;
	}

	/**
	 * Gets the person by created by.
	 *
	 * @return the person by created by
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Person getPersonByCreatedBy() {
		return this.personByCreatedBy;
	}

	/**
	 * Sets the person by created by.
	 *
	 * @param personByCreatedBy the new person by created by
	 */
	public void setPersonByCreatedBy(Person personByCreatedBy) {
		this.personByCreatedBy = personByCreatedBy;
	}

	/**
	 * Gets the tree species.
	 *
	 * @return the tree species
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tree_species_id", nullable = false)
	public TreeSpecies getTreeSpecies() {
		return this.treeSpecies;
	}

	/**
	 * Sets the tree species.
	 *
	 * @param treeSpecies the new tree species
	 */
	public void setTreeSpecies(TreeSpecies treeSpecies) {
		this.treeSpecies = treeSpecies;
	}

	/**
	 * Gets the person by changed by.
	 *
	 * @return the person by changed by
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "changed_by")
	public Person getPersonByChangedBy() {
		return this.personByChangedBy;
	}

	/**
	 * Sets the person by changed by.
	 *
	 * @param personByChangedBy the new person by changed by
	 */
	public void setPersonByChangedBy(Person personByChangedBy) {
		this.personByChangedBy = personByChangedBy;
	}

	/**
	 * Gets the prod type.
	 *
	 * @return the prod type
	 */
	@Column(name = "prod_type", nullable = false, length = 50)
	@Type(type = "com.geoland.kfis.persistence.hibernate.usertypes.ProdtypeUserType")
	public Prodtype getProdType() {
		return this.prodType;
	}

	/**
	 * Sets the prod type.
	 *
	 * @param prodType the new prod type
	 */
	public void setProdType(Prodtype prodType) {
		this.prodType = prodType;
	}

	/**
	 * Gets the age.
	 *
	 * @return the age
	 */
	@Column(name = "age", nullable = false)
	public Short getAge() {
		return this.age;
	}

	/**
	 * Sets the age.
	 *
	 * @param age the new age
	 */
	public void setAge(Short age) {
		this.age = age;
	}

	/**
	 * Gets the seed year.
	 *
	 * @return the seed year
	 */
	@Column(name = "seed_year", nullable = false)
	public Long getSeedYear() {
		return this.seedYear;
	}

	/**
	 * Sets the seed year.
	 *
	 * @param seedYear the new seed year
	 */
	public void setSeedYear(Long seedYear) {
		this.seedYear = seedYear;
	}

	/**
	 * Gets the stock.
	 *
	 * @return the stock
	 */
	@Column(name = "stock", nullable = false)
	public Long getStock() {
		return this.stock;
	}

	/**
	 * Sets the stock.
	 *
	 * @param stock the new stock
	 */
	public void setStock(Long stock) {
		this.stock = stock;
	}

	/**
	 * Gets the price.
	 *
	 * @return the price
	 */
	@Column(name = "price", precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	/**
	 * Sets the price.
	 *
	 * @param price the new price
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * Gets the changed date.
	 *
	 * @return the changed date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "changed_date", length = 29)
	public Date getChangedDate() {
		return this.changedDate;
	}

	/**
	 * Sets the changed date.
	 *
	 * @param changedDate the new changed date
	 */
	public void setChangedDate(Date changedDate) {
		this.changedDate = changedDate;
	}

	/**
	 * Gets the seedling inventory PO ss.
	 *
	 * @return the seedling inventory PO ss
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seedlingInventory")
	public Set<SeedlingInventoryPOS> getSeedlingInventoryPOSs() {
		return this.seedlingInventoryPOSs;
	}

	/**
	 * Sets the seedling inventory PO ss.
	 *
	 * @param seedlingInventoryPOSs the new seedling inventory PO ss
	 */
	public void setSeedlingInventoryPOSs(
			Set<SeedlingInventoryPOS> seedlingInventoryPOSs) {
		this.seedlingInventoryPOSs = seedlingInventoryPOSs;
	}

}
