package com.geoland.kfis.model;

// Generated Oct 6, 2015 4:18:04 PM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * ShapeTreatmentName generated by hbm2java.
 */
@Entity
@Table(name = "tshape_treatment_name", schema = "public")
public class ShapeTreatmentName extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The code. */
	private Long code;
	
	/** The name. */
	private String name;
	
	/** The name en. */
	private String nameEn;
	
	/** The name sr. */
	private String nameSr;
	
	/** The shape stand treatments. */
	private Set<ShapeStandTreatment> shapeStandTreatments = new HashSet<ShapeStandTreatment>(
			0);

	/**
	 * Instantiates a new shape treatment name.
	 */
	public ShapeTreatmentName() {
	}

	/**
	 * Instantiates a new shape treatment name.
	 *
	 * @param code the code
	 * @param name the name
	 */
	public ShapeTreatmentName(Long code, String name) {
		this.code = code;
		this.name = name;
	}

	/**
	 * Instantiates a new shape treatment name.
	 *
	 * @param code the code
	 * @param name the name
	 * @param nameEn the name en
	 * @param nameSr the name sr
	 * @param shapeStandTreatments the shape stand treatments
	 */
	public ShapeTreatmentName(Long code, String name, String nameEn,
			String nameSr, Set<ShapeStandTreatment> shapeStandTreatments) {
		this.code = code;
		this.name = name;
		this.nameEn = nameEn;
		this.nameSr = nameSr;
		this.shapeStandTreatments = shapeStandTreatments;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the code.
	 *
	 * @return the code
	 */
	@Column(name = "code", nullable = false)
	public Long getCode() {
		return this.code;
	}

	/**
	 * Sets the code.
	 *
	 * @param code the new code
	 */
	public void setCode(Long code) {
		this.code = code;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the name en.
	 *
	 * @return the name en
	 */
	@Column(name = "name_en")
	public String getNameEn() {
		return this.nameEn;
	}

	/**
	 * Sets the name en.
	 *
	 * @param nameEn the new name en
	 */
	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	/**
	 * Gets the name sr.
	 *
	 * @return the name sr
	 */
	@Column(name = "name_sr")
	public String getNameSr() {
		return this.nameSr;
	}

	/**
	 * Sets the name sr.
	 *
	 * @param nameSr the new name sr
	 */
	public void setNameSr(String nameSr) {
		this.nameSr = nameSr;
	}

	/**
	 * Gets the shape stand treatments.
	 *
	 * @return the shape stand treatments
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shapeTreatmentName")
	public Set<ShapeStandTreatment> getShapeStandTreatments() {
		return this.shapeStandTreatments;
	}

	/**
	 * Sets the shape stand treatments.
	 *
	 * @param shapeStandTreatments the new shape stand treatments
	 */
	public void setShapeStandTreatments(
			Set<ShapeStandTreatment> shapeStandTreatments) {
		this.shapeStandTreatments = shapeStandTreatments;
	}

}
