package com.geoland.kfis.model;

// Generated Oct 20, 2015 3:54:28 PM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * ShapePlotTrees generated by hbm2java.
 */
@Entity
@Table(name = "shape_plot_trees", schema = "public")
public class ShapePlotTrees extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The ogc fid. */
	private Long ogcFid;
	
	/** The plotid. */
	private BigDecimal plotid;
	
	/** The treeid. */
	private BigDecimal treeid;
	
	/** The health. */
	private BigDecimal health;
	
	/** The name. */
	private String name;
	
	/** The incomplete. */
	private BigDecimal incomplete;
	
	/** The height. */
	private BigDecimal height;
	
	/** The increment. */
	private BigDecimal increment;
	
	/** The diameter. */
	private BigDecimal diameter;
	
	/** The testmark. */
	private BigDecimal testmark;
	
	/** The plottreeid. */
	private String plottreeid;
	
	/** The speccode. */
	private BigDecimal speccode;
	
	/** The techcode. */
	private BigDecimal techcode;

	/**
	 * Instantiates a new shape plot trees.
	 */
	public ShapePlotTrees() {
	}

	/**
	 * Instantiates a new shape plot trees.
	 *
	 * @param plotid the plotid
	 * @param treeid the treeid
	 * @param health the health
	 * @param name the name
	 * @param incomplete the incomplete
	 * @param height the height
	 * @param increment the increment
	 * @param diameter the diameter
	 * @param testmark the testmark
	 * @param plottreeid the plottreeid
	 * @param speccode the speccode
	 * @param techcode the techcode
	 */
	public ShapePlotTrees(BigDecimal plotid, BigDecimal treeid,
			BigDecimal health, String name, BigDecimal incomplete,
			BigDecimal height, BigDecimal increment, BigDecimal diameter,
			BigDecimal testmark, String plottreeid, BigDecimal speccode,
			BigDecimal techcode) {
		this.plotid = plotid;
		this.treeid = treeid;
		this.health = health;
		this.name = name;
		this.incomplete = incomplete;
		this.height = height;
		this.increment = increment;
		this.diameter = diameter;
		this.testmark = testmark;
		this.plottreeid = plottreeid;
		this.speccode = speccode;
		this.techcode = techcode;
	}

	/**
	 * Gets the ogc fid.
	 *
	 * @return the ogc fid
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ogc_fid", unique = true, nullable = false)
	public Long getOgcFid() {
		return this.ogcFid;
	}

	/**
	 * Sets the ogc fid.
	 *
	 * @param ogcFid the new ogc fid
	 */
	public void setOgcFid(Long ogcFid) {
		this.ogcFid = ogcFid;
	}

	/**
	 * Gets the plotid.
	 *
	 * @return the plotid
	 */
	@Column(name = "plotid", precision = 9, scale = 0)
	public BigDecimal getPlotid() {
		return this.plotid;
	}

	/**
	 * Sets the plotid.
	 *
	 * @param plotid the new plotid
	 */
	public void setPlotid(BigDecimal plotid) {
		this.plotid = plotid;
	}

	/**
	 * Gets the treeid.
	 *
	 * @return the treeid
	 */
	@Column(name = "treeid", precision = 9, scale = 0)
	public BigDecimal getTreeid() {
		return this.treeid;
	}

	/**
	 * Sets the treeid.
	 *
	 * @param treeid the new treeid
	 */
	public void setTreeid(BigDecimal treeid) {
		this.treeid = treeid;
	}

	/**
	 * Gets the health.
	 *
	 * @return the health
	 */
	@Column(name = "health", precision = 9, scale = 0)
	public BigDecimal getHealth() {
		return this.health;
	}

	/**
	 * Sets the health.
	 *
	 * @param health the new health
	 */
	public void setHealth(BigDecimal health) {
		this.health = health;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", length = 28)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the incomplete.
	 *
	 * @return the incomplete
	 */
	@Column(name = "incomplete", scale = 11)
	public BigDecimal getIncomplete() {
		return this.incomplete;
	}

	/**
	 * Sets the incomplete.
	 *
	 * @param incomplete the new incomplete
	 */
	public void setIncomplete(BigDecimal incomplete) {
		this.incomplete = incomplete;
	}

	/**
	 * Gets the height.
	 *
	 * @return the height
	 */
	@Column(name = "height", precision = 9, scale = 0)
	public BigDecimal getHeight() {
		return this.height;
	}

	/**
	 * Sets the height.
	 *
	 * @param height the new height
	 */
	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	/**
	 * Gets the increment.
	 *
	 * @return the increment
	 */
	@Column(name = "increment", scale = 11)
	public BigDecimal getIncrement() {
		return this.increment;
	}

	/**
	 * Sets the increment.
	 *
	 * @param increment the new increment
	 */
	public void setIncrement(BigDecimal increment) {
		this.increment = increment;
	}

	/**
	 * Gets the diameter.
	 *
	 * @return the diameter
	 */
	@Column(name = "diameter", scale = 11)
	public BigDecimal getDiameter() {
		return this.diameter;
	}

	/**
	 * Sets the diameter.
	 *
	 * @param diameter the new diameter
	 */
	public void setDiameter(BigDecimal diameter) {
		this.diameter = diameter;
	}

	/**
	 * Gets the testmark.
	 *
	 * @return the testmark
	 */
	@Column(name = "testmark", scale = 11)
	public BigDecimal getTestmark() {
		return this.testmark;
	}

	/**
	 * Sets the testmark.
	 *
	 * @param testmark the new testmark
	 */
	public void setTestmark(BigDecimal testmark) {
		this.testmark = testmark;
	}

	/**
	 * Gets the plottreeid.
	 *
	 * @return the plottreeid
	 */
	@Column(name = "plottreeid", length = 12)
	public String getPlottreeid() {
		return this.plottreeid;
	}

	/**
	 * Sets the plottreeid.
	 *
	 * @param plottreeid the new plottreeid
	 */
	public void setPlottreeid(String plottreeid) {
		this.plottreeid = plottreeid;
	}

	/**
	 * Gets the speccode.
	 *
	 * @return the speccode
	 */
	@Column(name = "speccode", precision = 9, scale = 0)
	public BigDecimal getSpeccode() {
		return this.speccode;
	}

	/**
	 * Sets the speccode.
	 *
	 * @param speccode the new speccode
	 */
	public void setSpeccode(BigDecimal speccode) {
		this.speccode = speccode;
	}

	/**
	 * Gets the techcode.
	 *
	 * @return the techcode
	 */
	@Column(name = "techcode", precision = 9, scale = 0)
	public BigDecimal getTechcode() {
		return this.techcode;
	}

	/**
	 * Sets the techcode.
	 *
	 * @param techcode the new techcode
	 */
	public void setTechcode(BigDecimal techcode) {
		this.techcode = techcode;
	}

}
