package com.geoland.kfis.model;

// Generated Jan 7, 2016 4:50:54 PM by Hibernate Tools 3.4.0.CR1

import com.geoland.framework.persistence.base.*;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * StandHarvestImplDeclare generated by hbm2java.
 */
@Entity
@Table(name = "tfrm_stand_harvest_impl_declare", schema = "public")
public class StandHarvestImplDeclare extends AbstractPersistentObject implements
		java.io.Serializable {

	/** The id. */
	private Long id;
	
	/** The stand harvest impl transport. */
	private StandHarvestImplTransport standHarvestImplTransport;
	
	/** The person. */
	private Person person;
	
	/** The stand harvest activity. */
	private StandHarvestActivity standHarvestActivity;
	
	/** The tech volume. */
	private Double techVolume;
	
	/** The fire volume. */
	private Double fireVolume;
	
	/** The pulp volume. */
	private Double pulpVolume;
	
	/** The im date. */
	private Date imDate;
	
	/** The created date. */
	private Date createdDate;

	/**
	 * Instantiates a new stand harvest impl declare.
	 */
	public StandHarvestImplDeclare() {
	}

	/**
	 * Instantiates a new stand harvest impl declare.
	 *
	 * @param person the person
	 * @param standHarvestActivity the stand harvest activity
	 * @param techVolume the tech volume
	 * @param fireVolume the fire volume
	 * @param pulpVolume the pulp volume
	 * @param imDate the im date
	 * @param createdDate the created date
	 */
	public StandHarvestImplDeclare(Person person,
			StandHarvestActivity standHarvestActivity, Double techVolume,
			Double fireVolume, Double pulpVolume, Date imDate, Date createdDate) {
		this.person = person;
		this.standHarvestActivity = standHarvestActivity;
		this.techVolume = techVolume;
		this.fireVolume = fireVolume;
		this.pulpVolume = pulpVolume;
		this.imDate = imDate;
		this.createdDate = createdDate;
	}

	/**
	 * Instantiates a new stand harvest impl declare.
	 *
	 * @param standHarvestImplTransport the stand harvest impl transport
	 * @param person the person
	 * @param standHarvestActivity the stand harvest activity
	 * @param techVolume the tech volume
	 * @param fireVolume the fire volume
	 * @param pulpVolume the pulp volume
	 * @param imDate the im date
	 * @param createdDate the created date
	 */
	public StandHarvestImplDeclare(
			StandHarvestImplTransport standHarvestImplTransport, Person person,
			StandHarvestActivity standHarvestActivity, Double techVolume,
			Double fireVolume, Double pulpVolume, Date imDate, Date createdDate) {
		this.standHarvestImplTransport = standHarvestImplTransport;
		this.person = person;
		this.standHarvestActivity = standHarvestActivity;
		this.techVolume = techVolume;
		this.fireVolume = fireVolume;
		this.pulpVolume = pulpVolume;
		this.imDate = imDate;
		this.createdDate = createdDate;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the stand harvest impl transport.
	 *
	 * @return the stand harvest impl transport
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transport_id")
	public StandHarvestImplTransport getStandHarvestImplTransport() {
		return this.standHarvestImplTransport;
	}

	/**
	 * Sets the stand harvest impl transport.
	 *
	 * @param standHarvestImplTransport the new stand harvest impl transport
	 */
	public void setStandHarvestImplTransport(
			StandHarvestImplTransport standHarvestImplTransport) {
		this.standHarvestImplTransport = standHarvestImplTransport;
	}

	/**
	 * Gets the person.
	 *
	 * @return the person
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	/**
	 * Sets the person.
	 *
	 * @param person the new person
	 */
	public void setPerson(Person person) {
		this.person = person;
	}

	/**
	 * Gets the stand harvest activity.
	 *
	 * @return the stand harvest activity
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "harvest_activity_id", nullable = false)
	public StandHarvestActivity getStandHarvestActivity() {
		return this.standHarvestActivity;
	}

	/**
	 * Sets the stand harvest activity.
	 *
	 * @param standHarvestActivity the new stand harvest activity
	 */
	public void setStandHarvestActivity(
			StandHarvestActivity standHarvestActivity) {
		this.standHarvestActivity = standHarvestActivity;
	}

	/**
	 * Gets the tech volume.
	 *
	 * @return the tech volume
	 */
	@Column(name = "tech_volume", nullable = false, precision = 17, scale = 17)
	public Double getTechVolume() {
		return this.techVolume;
	}

	/**
	 * Sets the tech volume.
	 *
	 * @param techVolume the new tech volume
	 */
	public void setTechVolume(Double techVolume) {
		this.techVolume = techVolume;
	}

	/**
	 * Gets the fire volume.
	 *
	 * @return the fire volume
	 */
	@Column(name = "fire_volume", nullable = false, precision = 17, scale = 17)
	public Double getFireVolume() {
		return this.fireVolume;
	}

	/**
	 * Sets the fire volume.
	 *
	 * @param fireVolume the new fire volume
	 */
	public void setFireVolume(Double fireVolume) {
		this.fireVolume = fireVolume;
	}

	/**
	 * Gets the pulp volume.
	 *
	 * @return the pulp volume
	 */
	@Column(name = "pulp_volume", nullable = false, precision = 17, scale = 17)
	public Double getPulpVolume() {
		return this.pulpVolume;
	}

	/**
	 * Sets the pulp volume.
	 *
	 * @param pulpVolume the new pulp volume
	 */
	public void setPulpVolume(Double pulpVolume) {
		this.pulpVolume = pulpVolume;
	}

	/**
	 * Gets the im date.
	 *
	 * @return the im date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "im_date", nullable = false, length = 13)
	public Date getImDate() {
		return this.imDate;
	}

	/**
	 * Sets the im date.
	 *
	 * @param imDate the new im date
	 */
	public void setImDate(Date imDate) {
		this.imDate = imDate;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
