package com.geoland.kfis.model;

// Generated Jul 6, 2015 1:29:43 PM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;
import org.hibernate.annotations.Type;
import com.geoland.kfis.persistence.hibernate.usertypes.Treespeciesgroup;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * StandSilvicultureActivity generated by hbm2java.
 */
@Entity
@Table(name = "tfrm_stand_silviculture_activity", schema = "public")
public class StandSilvicultureActivity extends AbstractPersistentObject
		implements java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The stand. */
	private Stand stand;
	
	/** The person by im created by. */
	private Person personByImCreatedBy;
	
	/** The activity. */
	private Activity activity;
	
	/** The activity status. */
	private ActivityStatus activityStatus;
	
	/** The person by pl created by. */
	private Person personByPlCreatedBy;
	
	/** The tree species group. */
	private Treespeciesgroup treeSpeciesGroup;
	
	/** The work stage. */
	private String workStage;
	
	/** The pl area. */
	private Double plArea;
	
	/** The pl created date. */
	private Date plCreatedDate;
	
	/** The im area. */
	private Double imArea;
	
	/** The im created date. */
	private Date imCreatedDate;

	/**
	 * Instantiates a new stand silviculture activity.
	 */
	public StandSilvicultureActivity() {
	}

	/**
	 * Instantiates a new stand silviculture activity.
	 *
	 * @param stand the stand
	 * @param activity the activity
	 * @param activityStatus the activity status
	 * @param workStage the work stage
	 */
	public StandSilvicultureActivity(Stand stand, Activity activity,
			ActivityStatus activityStatus, String workStage) {
		this.stand = stand;
		this.activity = activity;
		this.activityStatus = activityStatus;
		this.workStage = workStage;
	}

	/**
	 * Instantiates a new stand silviculture activity.
	 *
	 * @param stand the stand
	 * @param personByImCreatedBy the person by im created by
	 * @param activity the activity
	 * @param activityStatus the activity status
	 * @param personByPlCreatedBy the person by pl created by
	 * @param treeSpeciesGroup the tree species group
	 * @param workStage the work stage
	 * @param plArea the pl area
	 * @param plCreatedDate the pl created date
	 * @param imArea the im area
	 * @param imCreatedDate the im created date
	 */
	public StandSilvicultureActivity(Stand stand, Person personByImCreatedBy,
			Activity activity, ActivityStatus activityStatus,
			Person personByPlCreatedBy, Treespeciesgroup treeSpeciesGroup,
			String workStage, Double plArea, Date plCreatedDate, Double imArea,
			Date imCreatedDate) {
		this.stand = stand;
		this.personByImCreatedBy = personByImCreatedBy;
		this.activity = activity;
		this.activityStatus = activityStatus;
		this.personByPlCreatedBy = personByPlCreatedBy;
		this.treeSpeciesGroup = treeSpeciesGroup;
		this.workStage = workStage;
		this.plArea = plArea;
		this.plCreatedDate = plCreatedDate;
		this.imArea = imArea;
		this.imCreatedDate = imCreatedDate;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the stand.
	 *
	 * @return the stand
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stand_id", nullable = false)
	public Stand getStand() {
		return this.stand;
	}

	/**
	 * Sets the stand.
	 *
	 * @param stand the new stand
	 */
	public void setStand(Stand stand) {
		this.stand = stand;
	}

	/**
	 * Gets the person by im created by.
	 *
	 * @return the person by im created by
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "im_created_by")
	public Person getPersonByImCreatedBy() {
		return this.personByImCreatedBy;
	}

	/**
	 * Sets the person by im created by.
	 *
	 * @param personByImCreatedBy the new person by im created by
	 */
	public void setPersonByImCreatedBy(Person personByImCreatedBy) {
		this.personByImCreatedBy = personByImCreatedBy;
	}

	/**
	 * Gets the activity.
	 *
	 * @return the activity
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "activity_id", nullable = false)
	public Activity getActivity() {
		return this.activity;
	}

	/**
	 * Sets the activity.
	 *
	 * @param activity the new activity
	 */
	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	/**
	 * Gets the activity status.
	 *
	 * @return the activity status
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id", nullable = false)
	public ActivityStatus getActivityStatus() {
		return this.activityStatus;
	}

	/**
	 * Sets the activity status.
	 *
	 * @param activityStatus the new activity status
	 */
	public void setActivityStatus(ActivityStatus activityStatus) {
		this.activityStatus = activityStatus;
	}

	/**
	 * Gets the person by pl created by.
	 *
	 * @return the person by pl created by
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pl_created_by")
	public Person getPersonByPlCreatedBy() {
		return this.personByPlCreatedBy;
	}

	/**
	 * Sets the person by pl created by.
	 *
	 * @param personByPlCreatedBy the new person by pl created by
	 */
	public void setPersonByPlCreatedBy(Person personByPlCreatedBy) {
		this.personByPlCreatedBy = personByPlCreatedBy;
	}

	/**
	 * Gets the tree species group.
	 *
	 * @return the tree species group
	 */
	@Column(name = "tree_species_group")
	@Type(type = "com.geoland.kfis.persistence.hibernate.usertypes.TreespeciesgroupUserType")
	public Treespeciesgroup getTreeSpeciesGroup() {
		return this.treeSpeciesGroup;
	}

	/**
	 * Sets the tree species group.
	 *
	 * @param treeSpeciesGroup the new tree species group
	 */
	public void setTreeSpeciesGroup(Treespeciesgroup treeSpeciesGroup) {
		this.treeSpeciesGroup = treeSpeciesGroup;
	}

	/**
	 * Gets the work stage.
	 *
	 * @return the work stage
	 */
	@Column(name = "work_stage", nullable = false, length = 1)
	public String getWorkStage() {
		return this.workStage;
	}

	/**
	 * Sets the work stage.
	 *
	 * @param workStage the new work stage
	 */
	public void setWorkStage(String workStage) {
		this.workStage = workStage;
	}

	/**
	 * Gets the pl area.
	 *
	 * @return the pl area
	 */
	@Column(name = "pl_area", precision = 17, scale = 17)
	public Double getPlArea() {
		return this.plArea;
	}

	/**
	 * Sets the pl area.
	 *
	 * @param plArea the new pl area
	 */
	public void setPlArea(Double plArea) {
		this.plArea = plArea;
	}

	/**
	 * Gets the pl created date.
	 *
	 * @return the pl created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pl_created_date", length = 29)
	public Date getPlCreatedDate() {
		return this.plCreatedDate;
	}

	/**
	 * Sets the pl created date.
	 *
	 * @param plCreatedDate the new pl created date
	 */
	public void setPlCreatedDate(Date plCreatedDate) {
		this.plCreatedDate = plCreatedDate;
	}

	/**
	 * Gets the im area.
	 *
	 * @return the im area
	 */
	@Column(name = "im_area", precision = 17, scale = 17)
	public Double getImArea() {
		return this.imArea;
	}

	/**
	 * Sets the im area.
	 *
	 * @param imArea the new im area
	 */
	public void setImArea(Double imArea) {
		this.imArea = imArea;
	}

	/**
	 * Gets the im created date.
	 *
	 * @return the im created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "im_created_date", length = 29)
	public Date getImCreatedDate() {
		return this.imCreatedDate;
	}

	/**
	 * Sets the im created date.
	 *
	 * @param imCreatedDate the new im created date
	 */
	public void setImCreatedDate(Date imCreatedDate) {
		this.imCreatedDate = imCreatedDate;
	}

}
