package com.geoland.kfis.model;

// Generated Nov 12, 2015 1:35:39 PM by Hibernate Tools 4.0.0

import com.geoland.framework.persistence.base.*;

import org.hibernate.annotations.Type;
import org.hibernate.annotations.TypeDef;
import org.hibernate.spatial.GeometryType;
import com.vividsolutions.jts.geom.Geometry;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * StandSilvicultureImplDeclare generated by hbm2java.
 */
@Entity
@Table(name = "tfrm_stand_silviculture_impl_declare", schema = "public")
@TypeDef(name = "geometry", typeClass = GeometryType.class)
public class StandSilvicultureImplDeclare extends AbstractPersistentObject
		implements java.io.Serializable {

	/** The id. */
	private Long id;
	
	/** The stand silviculture activity. */
	private StandSilvicultureActivity standSilvicultureActivity;
	
	/** The person. */
	private Person person;
	
	/** The im area. */
	private Double imArea;
	
	/** The im date. */
	private Date imDate;
	
	/** The created date. */
	private Date createdDate;
	
	/** The im geom. */
	private Geometry imGeom;

	/**
	 * Instantiates a new stand silviculture impl declare.
	 */
	public StandSilvicultureImplDeclare() {
	}

	/**
	 * Instantiates a new stand silviculture impl declare.
	 *
	 * @param standSilvicultureActivity the stand silviculture activity
	 * @param person the person
	 * @param imArea the im area
	 * @param imDate the im date
	 * @param createdDate the created date
	 * @param imGeom the im geom
	 */
	public StandSilvicultureImplDeclare(
			StandSilvicultureActivity standSilvicultureActivity, Person person,
			Double imArea, Date imDate, Date createdDate, Geometry imGeom) {
		this.standSilvicultureActivity = standSilvicultureActivity;
		this.person = person;
		this.imArea = imArea;
		this.imDate = imDate;
		this.createdDate = createdDate;
		this.imGeom = imGeom;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the stand silviculture activity.
	 *
	 * @return the stand silviculture activity
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "slv_activity_id", nullable = false)
	public StandSilvicultureActivity getStandSilvicultureActivity() {
		return this.standSilvicultureActivity;
	}

	/**
	 * Sets the stand silviculture activity.
	 *
	 * @param standSilvicultureActivity the new stand silviculture activity
	 */
	public void setStandSilvicultureActivity(
			StandSilvicultureActivity standSilvicultureActivity) {
		this.standSilvicultureActivity = standSilvicultureActivity;
	}

	/**
	 * Gets the person.
	 *
	 * @return the person
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	/**
	 * Sets the person.
	 *
	 * @param person the new person
	 */
	public void setPerson(Person person) {
		this.person = person;
	}

	/**
	 * Gets the im area.
	 *
	 * @return the im area
	 */
	@Column(name = "im_area", nullable = false, precision = 17, scale = 17)
	public Double getImArea() {
		return this.imArea;
	}

	/**
	 * Sets the im area.
	 *
	 * @param imArea the new im area
	 */
	public void setImArea(Double imArea) {
		this.imArea = imArea;
	}

	/**
	 * Gets the im date.
	 *
	 * @return the im date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "im_date", nullable = false, length = 13)
	public Date getImDate() {
		return this.imDate;
	}

	/**
	 * Sets the im date.
	 *
	 * @param imDate the new im date
	 */
	public void setImDate(Date imDate) {
		this.imDate = imDate;
	}

	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * Gets the im geom.
	 *
	 * @return the im geom
	 */
	@Column(name = "im_geom", nullable = false)
	@Type(type = "org.hibernate.spatial.GeometryType")
	public Geometry getImGeom() {
		return this.imGeom;
	}

	/**
	 * Sets the im geom.
	 *
	 * @param imGeom the new im geom
	 */
	public void setImGeom(Geometry imGeom) {
		this.imGeom = imGeom;
	}

}
