package com.geoland.kfis.model;

// Generated Feb 11, 2015 2:26:59 AM by Hibernate Tools 3.4.0.CR1

import com.geoland.framework.persistence.base.*;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

// TODO: Auto-generated Javadoc
/**
 * VehicleRegister generated by hbm2java.
 */
@Entity
@Table(name = "tlog_vehicles_register", schema = "public")
public class VehicleRegister extends AbstractPersistentObject implements
		java.io.Serializable {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Long id;
	
	/** The employee. */
	private Employee employee;
	
	/** The vehicle. */
	private Vehicle vehicle;
	
	/** The registered date. */
	private Date registeredDate;
	
	/** The valide to date. */
	private Date valideToDate;
	
	/** The mileage at register. */
	private String mileageAtRegister;
	
	/** The created time. */
	private Date createdTime;

	/**
	 * Instantiates a new vehicle register.
	 */
	public VehicleRegister() {
	}

	/**
	 * Instantiates a new vehicle register.
	 *
	 * @param employee the employee
	 * @param vehicle the vehicle
	 * @param registeredDate the registered date
	 * @param valideToDate the valide to date
	 * @param createdTime the created time
	 */
	public VehicleRegister(Employee employee, Vehicle vehicle,
			Date registeredDate, Date valideToDate, Date createdTime) {
		this.employee = employee;
		this.vehicle = vehicle;
		this.registeredDate = registeredDate;
		this.valideToDate = valideToDate;
		this.createdTime = createdTime;
	}

	/**
	 * Instantiates a new vehicle register.
	 *
	 * @param employee the employee
	 * @param vehicle the vehicle
	 * @param registeredDate the registered date
	 * @param valideToDate the valide to date
	 * @param mileageAtRegister the mileage at register
	 * @param createdTime the created time
	 */
	public VehicleRegister(Employee employee, Vehicle vehicle,
			Date registeredDate, Date valideToDate, String mileageAtRegister,
			Date createdTime) {
		this.employee = employee;
		this.vehicle = vehicle;
		this.registeredDate = registeredDate;
		this.valideToDate = valideToDate;
		this.mileageAtRegister = mileageAtRegister;
		this.createdTime = createdTime;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#getId()
	 */
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/* (non-Javadoc)
	 * @see com.geoland.framework.persistence.base.AbstractPersistentObject#setId(java.lang.Long)
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Gets the employee.
	 *
	 * @return the employee
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "created_by", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Sets the employee.
	 *
	 * @param employee the new employee
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	/**
	 * Gets the vehicle.
	 *
	 * @return the vehicle
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vehicles_id", nullable = false)
	public Vehicle getVehicle() {
		return this.vehicle;
	}

	/**
	 * Sets the vehicle.
	 *
	 * @param vehicle the new vehicle
	 */
	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	/**
	 * Gets the registered date.
	 *
	 * @return the registered date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "registered_date", nullable = false, length = 13)
	public Date getRegisteredDate() {
		return this.registeredDate;
	}

	/**
	 * Sets the registered date.
	 *
	 * @param registeredDate the new registered date
	 */
	public void setRegisteredDate(Date registeredDate) {
		this.registeredDate = registeredDate;
	}

	/**
	 * Gets the valide to date.
	 *
	 * @return the valide to date
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "valide_to_date", nullable = false, length = 13)
	public Date getValideToDate() {
		return this.valideToDate;
	}

	/**
	 * Sets the valide to date.
	 *
	 * @param valideToDate the new valide to date
	 */
	public void setValideToDate(Date valideToDate) {
		this.valideToDate = valideToDate;
	}

	/**
	 * Gets the mileage at register.
	 *
	 * @return the mileage at register
	 */
	@Column(name = "mileage_at_register", length = 20)
	public String getMileageAtRegister() {
		return this.mileageAtRegister;
	}

	/**
	 * Sets the mileage at register.
	 *
	 * @param mileageAtRegister the new mileage at register
	 */
	public void setMileageAtRegister(String mileageAtRegister) {
		this.mileageAtRegister = mileageAtRegister;
	}

	/**
	 * Gets the created time.
	 *
	 * @return the created time
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 29)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	/**
	 * Sets the created time.
	 *
	 * @param createdTime the new created time
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
