SELECT FIN.MUNICIPALITY_ID, ORG.ORGA_NAME AS ORGA_NAME, SUM(FIN.CUMULATIVE_VALUE)
  FROM
       TFIN_INPUT AS FIN LEFT OUTER JOIN TORGANISATION_MUN AS ORG_MUN ON FIN.MUNICIPALITY_ID = ORG_MUN.MUN_ID LEFT OUTER JOIN TORGANISATION AS ORG ON ORG.ID = FIN.MUNICIPALITY_ID LEFT OUTER JOIN TGIS_CADASTRAL_MUNICIPALITY AS CAD ON CAD.ID = ORG_MUN.MUN_ID
  GROUP BY FIN.MUNICIPALITY_ID, ORG.ORGA_NAME