DROP TABLE IF EXISTS TRBAC_USER_HAS_ROLE  CASCADE;
DROP TABLE IF EXISTS TRBAC_ROLE_HAS_DOMAIN_PRIVILEGE CASCADE;
DROP TABLE IF EXISTS TRBAC_DOMAIN_HAS_OBJECT CASCADE;
DROP TABLE IF EXISTS TRBAC_PRIVILEGE_HAS_ACTION CASCADE;
DROP TABLE IF EXISTS TRBAC_PRIVILEGE CASCADE;
DROP TABLE IF EXISTS TRBAC_DOMAIN CASCADE;
DROP TABLE IF EXISTS TRBAC_ACTION CASCADE;
DROP TABLE IF EXISTS TRBAC_OBJECT CASCADE;
DROP TABLE IF EXISTS TRBAC_ROLE  CASCADE;
DROP TABLE IF EXISTS TDOMAIN CASCADE;

/* TABLE ROLE BASED ACESS CONTROLE */
CREATE TABLE TRBAC_ROLE
(
	ID SERIAL PRIMARY KEY NOT NULL,
	NAME VARCHAR(50) NOT NULL UNIQUE,
	DESCRIPTION TEXT,
	IMPORTANCE SMALLINT NOT NULL
);
CREATE TABLE TRBAC_OBJECT
(
	ID SERIAL PRIMARY KEY NOT NULL,
	NAME VARCHAR(50) NOT NULL UNIQUE,
	DESCRIPTION TEXT,
	IS_SINGULAR BOOLEAN NOT NULL
);
CREATE TABLE TRBAC_ACTION
(
	ID SERIAL PRIMARY KEY NOT NULL,
	NAME VARCHAR(50) NOT NULL UNIQUE,
	DESCRIPTION TEXT
);
CREATE TABLE TRBAC_DOMAIN
(
	ID SERIAL PRIMARY KEY NOT NULL,
	NAME VARCHAR(50) NOT NULL UNIQUE,
	DESCRIPTION TEXT,
	IS_SINGULAR BOOLEAN NOT NULL
);
CREATE TABLE TRBAC_PRIVILEGE
(
	ID SERIAL PRIMARY KEY NOT NULL,
	NAME VARCHAR(50) NOT NULL UNIQUE,
	DESCRIPTION TEXT,
	IS_SINGULAR BOOLEAN NOT NULL
);
CREATE TABLE TRBAC_PRIVILEGE_HAS_ACTION
(
	ID SERIAL PRIMARY KEY NOT NULL,
	PRIVILEGE_ID INT NOT NULL,
	ACTION_ID INT NOT NULL,
	UNIQUE (PRIVILEGE_ID, ACTION_ID),
	FOREIGN KEY (PRIVILEGE_ID) REFERENCES TRBAC_PRIVILEGE(ID),
	FOREIGN KEY (ACTION_ID) REFERENCES TRBAC_ACTION(ID)
);
CREATE TABLE TRBAC_DOMAIN_HAS_OBJECT
(
	ID SERIAL PRIMARY KEY NOT NULL,
	DOMAIN_ID INT NOT NULL,
	OBJECT_ID INT NOT NULL,
	UNIQUE (DOMAIN_ID, OBJECT_ID),
	FOREIGN KEY (DOMAIN_ID) REFERENCES TRBAC_DOMAIN(ID),
	FOREIGN KEY (OBJECT_ID) REFERENCES TRBAC_OBJECT(ID)
);
CREATE TABLE TRBAC_ROLE_HAS_DOMAIN_PRIVILEGE
(
	ID SERIAL PRIMARY KEY NOT NULL,
	ROLE_ID INT NOT NULL,
	PRIVILEGE_ID INT NOT NULL,
	DOMAIN_ID INT NOT NULL,
	IS_ALLOWED BOOLEAN NOT NULL,
	UNIQUE (ROLE_ID, PRIVILEGE_ID, DOMAIN_ID),
	FOREIGN KEY (ROLE_ID) REFERENCES TRBAC_ROLE(ID),
	FOREIGN KEY (PRIVILEGE_ID) REFERENCES TRBAC_PRIVILEGE(ID),
	FOREIGN KEY (DOMAIN_ID) REFERENCES TRBAC_DOMAIN(ID)
);
CREATE TABLE TDOMAIN
(
	ID SERIAL PRIMARY KEY,
	DOMNAME VARCHAR(18) NOT NULL,
	COLNAME VARCHAR(18) NOT NULL,
	TABNAME VARCHAR(30) NOT NULL,
	DOMTYPE CHAR(1) NOT NULL,
	COLLLENGTH INTEGER NOT NULL,
	MANDATORY CHAR(1) NOT NULL
);
ALTER TABLE TDOMAIN OWNER TO POSTGRES;